### ISSUE TITLE
Governance page formatting

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#10]
The governance page has a huge chunk of white space between the first and second columns. 

There are also some extra `<div>` elements at the bottom of the list of Executive Council members. 

@tracykteal - If the Executive Director is listed on the Governance page, should the Associate Director also be listed?

**Comment by weaverbel** [comment]
I have removed the column set up and added EB as well.

**Comment by weaverbel** [comment]
Closing this for now.
