### ISSUE TITLE
add 'why teach' testimonials to teach.md

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#100]
I think we have testimonials from Beth Duckles and @weaverbel's work on why people teach. We could create a testimonials page for why people teach and link to it from the teach.md page.

**Comment by maneesha** [comment]
Trying to clean up some very old issues :-)

@karenword  @klbarnes20  Is this something you'd like to revisit?

**Comment by maneesha** [comment]
@kmomar  Do you feel this is covered in the recent revamp you did of the testimonials page? https://carpentries.org/testimonials/

**Comment by kmomar** [comment]
@maneesha I think we can close this issue. Generally, the current testimonials are more focused on what people have taken away from workshops, but we can create a new section or just add testimonials from Instructors, but we can definitely close this one.
