### ISSUE TITLE
New page for past Executive Council members

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#1004]
With time, the list of past EC members on https://carpentries.org/governance/ is growing and the information at the bottom becomes a bit drowned out. Would it be a good idea to make a separate page for past EC members?

**Comment by maneesha** [comment]
Thanks for suggesting this @lexnederbragt  
I can create a separate page for previous years' Executive Council members once the 2021 Executive Council  information is updated.  Based on #1005 I believe @konrad  is working on this.

**Comment by konrad** [comment]
I have added the 2021 EC for as discussed in issue #1004 in PR #1011.
