### ISSUE TITLE
update Governance page with new EC composition information

### ISSUE THREAD

**Issue by serahkiburu** [carpentries/carpentries.org-archive#1005]
Now that we have the new Executive Council in place, it would be good to update the Governance page on the website with this information, and perhaps listing the specific EC committees and their composition and role in driving governance. 

cc @kariljordan @lexnederbragt @sstevens2

**Comment by lexnederbragt** [comment]
Internally already assigned to @konrad.

**Comment by serahkiburu** [comment]
thank you @lexnederbragt @konrad
