### ISSUE TITLE
map of instructors

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#101]
We could create a map of where all our instructors are and include a link to that map from the teach.md page. Ideally it would update regularly and automatically.

**Comment by jduckles** [comment]
I can get this going when I have some time next week.

**Comment by maneesha** [comment]
We already have this on the SWC site.  Can we migrate this to the Carpentries site?

**Comment by weaverbel** [comment]
We also need to migrate all the bios and images - this is a big job.

**Comment by maneesha** [comment]
We should also say something on the page to the effect of   "If your bio/image is not up or you want it updated please email instructorbio@carpentries.org"

**Comment by weaverbel** [comment]
Do you mean add this to the SWC page @maneesha ?

**Comment by jduckles** [comment]
Data feeds are in place for this and part of the website repo in `amy/*.json` as detailed in the `README.md` here: https://github.com/carpentries/amy-feeds

**Comment by weaverbel** [comment]
So are you taking the lead on this @jduckles ? Or is it @maneesha? And where does this fit in with the privacy changes? Are we only getting feeds of data from people who have given explicit permissions? I am assuming yes?

**Comment by jduckles** [comment]
The data automation part is done in the above repo. Got that working today. The next step should be fairly easy, but will have to be done either 1 or 3 times depending on if we want a map of SWC,DC,ALL instructors. I've made data feeds for each. I'm inclined to go with ALL only. Feeds for the instructor profiles is a separate issue #80

**Comment by weaverbel** [comment]
I think we can close this now we have the new instructor page.

**Comment by jduckles** [comment]
I've ported the SWC map over to https://carpentries.org/instructors-map/ using a json feed of all instructors from https://github.com/carpentries/amy-feeds
