### ISSUE TITLE
Member Organizations under About?

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#102]
Rather than having 'Member Organizations' under 'Join Us', should we put it under 'About'?

Might also be related to getting updated member organization information.
https://github.com/carpentries/carpentries.org/issues/98

@jduckles @elizabethwilliams8 do you have thoughts on the best place for 'Member Organizations' as a category?

**Comment by elizabethwilliams8** [comment]
This is a tough one. I think I actually would like it best under 'Our Team' along with the other lists of categories of the community. 'About Us' doesn't include other lists, and our maintainers, instructors and staff are 'Us' just as much as member organizations, so it feels a bit awkward there (this thought led to including members in Team). 'Join Us' would be my next vote, but I'm not sure that this is where people would look for a list of members from the home page.

**Comment by weaverbel** [comment]
I think it belongs under both `Join us` and `About` - it doesn't hurt to have stuff linked from two places. Our existing members are a big part of our `About story`, but we also want new members to join.

**Comment by weaverbel** [comment]
I have added Current ... to About menu - what do people think?

**Comment by elizabethwilliams8** [comment]
Looks good to me! Will trust your instincts about differentiating the members from the team @weaverbel

**Comment by tracykteal** [comment]
Looks good to me. Closing.
