### ISSUE TITLE
Enroll in GitHub Sponsors

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/carpentries.org-archive#1023]
I think all The Carpentries' Github organizations (carpentries, swcarpentry, datacarpentry, and librarycarpentry) should apply for GitHub Sponsors:

![Screen Shot 2021-03-11 at 12 15 35](https://user-images.githubusercontent.com/13123663/110834850-ae258600-8263-11eb-8e39-03df48a19fe8.png)

**Comment by zkamvar** [comment]
I do not see this on the page you linked or any of the other pages. Do you have a new GitHub feature enabled?

**Comment by maxim-belkin** [comment]
I don't think "GitHub Sponsors" is a new feature... do you not see the "Sponsor" button?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/13123663/110845336-22febd00-8270-11eb-9185-19a60fa24a58.png)
</details>

Information about Github sponsors can be found here: https://github.com/sponsors

**Comment by zkamvar** [comment]
I see the sponsors button, but I don't see that big red error that you posted on your screenshot. We have it set to custom at the moment: https://github.com/carpentries/.github/blob/master/FUNDING.yml

**Comment by maxim-belkin** [comment]
You have to go to https://github.com/swcarpentry/r-novice-gapminder/ and click on "Sponsor" there to see that message.

**Comment by zkamvar** [comment]
Ah! Thank you for the clarification! That's a good point.

**Comment by fmichonneau** [comment]
Thanks for reporting this Maxim. Because of our fiscal sponsorship status, it's a little tricky. We had started the process before the pandemic hit and didn't finish pursuing it. We are going to look into this more.

**Comment by maxim-belkin** [comment]
Got it. Thanks, François. Feel free to close this if this is on your radar and/or todo list somewhere.

**Comment by maneesha** [comment]
@fmichonneau  Do you want to keep this open?

**Comment by fmichonneau** [comment]
yes, we're working on it. cc @ErinBecker @Al-Obayuwana

**Comment by Al-Obayuwana** [comment]
Thanks Kari and I spoke and we are working on a plan. @maxim-belkin I would love to hear some of your ideas for our plan as well if you would like to share.

**Comment by maxim-belkin** [comment]
> Thanks Kari and I spoke and we are working on a plan. @maxim-belkin I would love to hear some of your ideas for our plan as well if you would like to share.

I'd be happy to share my ideas, @Al-Obayuwana, if you can point me to a page that describes the plan.

**Comment by maneesha** [comment]
How ever this gets set up, we should be sure we are using the correct fundraising link.  See https://github.com/carpentries/carpentries.org/issues/1150

**Comment by maneesha** [comment]
@fmichonneau Can this be closed now?

**Comment by fmichonneau** [comment]
Yes, thanks Maneesha!
