### ISSUE TITLE
Add links to Matrix rooms on "Connecting with The Carpentries" page

### ISSUE THREAD

**Issue by jezcope** [carpentries/carpentries.org-archive#1026]
Hey folks, a few of you may know that I and a handful of others have been accessing the Carpentries Slack via the [Matrix network](https://matrix.org/), by bridging matrix rooms to Slack channels in a 1:1 relationship.

Until now I've kept most of the matrix rooms private as it's a little experimental and very unofficial, but now Matrix is growing in use I'd love to open them up as another way for folks to engage with the Carpentries. Since anyone can request an invite to this slack space, it would be consistent to make the matrix rooms open and freely joinable too, I think, and link them from [Connecting with The Carpentries](https://carpentries.org/connect/).

Matrix rooms can be joinable by link, so they could be linked on the Carpentries website without being fully public. On top of this rooms can be added to the global room directory: after a similar conversation a while back I opened up the [Matrix version of the #general Slack channel](https://matrix.to/#/#carpentries-general:matrix.org) in this way and we had a new person discover us through that route only a few weeks ago, which is nice.

There is no history limit on Matrix, so it provides a way of accessing older conversations, for good or ill (note that older messages aren't actually lost in Slack either, just hidden until and unless someone upgrades it to a paid space).

As part of this I'd want 2-3 people to volunteer as moderators with Matrix accounts besides me to ensure our CoC can be enforced, and it's not something I'd want to do unilaterally, so what do others think?

**Comment by maneesha** [comment]
Thanks for bringing this up @jezcope 
Tagging @fmichonneau for input on this, to see if we should include Matrix in our official channels.

**Comment by maneesha** [comment]
I've discussed this with @jezcope  and @fmichonneau  
We'll be reviewing how Matrix works in the next few weeks to make a decision.

**Comment by maneesha** [comment]
We are continuing to discuss this internally to understand the benefits of maintaining and promoting Matrix in addition to Slack.

**Comment by maneesha** [comment]
@fmichonneau Do you want to keep this open?

**Comment by maneesha** [comment]
I am closing this issue because there are no significant benefits of maintaining and promoting Matrix in addition to Slack, given the time and effort it would require.
