### ISSUE TITLE
Slack invitation link is broken

### ISSUE THREAD

**Issue by shuuji3** [carpentries/carpentries.org-archive#1082]
Hello🙂

[Community Overview](https://carpentries.org/community/) has Slack invitation links (https://swc-slack-invite.herokuapp.com/). But currently, it seems that the page is broken and newcomers (like me) cannot join the Slack channel. Could you fix the link? Thank you.

**Screenshot**

<img width="563" alt="Screen Shot 2021-06-01 at 0 18 25" src="https://user-images.githubusercontent.com/1425259/120214351-52b9d180-c26f-11eb-95c8-fa513eb0a6e0.png">

**Comment by fmichonneau** [comment]
it should be back online now. Thanks for reporting. Thanks!

**Comment by shuuji3** [comment]
Thank you for the quick fix. It works now. Thanks!

<img width="414" alt="Screen Shot 2021-06-01 at 22 33 59" src="https://user-images.githubusercontent.com/1425259/120332650-ebad2300-c329-11eb-9778-0d3dd9420fdf.png">
