### ISSUE TITLE
Updating Core Team teams page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#1086]
The team membership information is a bit outdated on the [Core Team teams page](https://carpentries.org/core-team-projects/). Could this please be updated based on the information in the CT onboarding packet?

**Comment by ErinBecker** [comment]
I've just pushed changes to the CT onboarding packet updating the team members and team leads. There will be additional changes in the next month, but please update to the current membership/leadership roles when possible.

**Comment by maneesha** [comment]
I can work on this.  Right now the list of names in each team is most often alpha by first name but is not consistently so.  @ErinBecker  do you have a preference for how they are listed?  
Also should the teams page identify the team leads? It does not currently.

**Comment by ErinBecker** [comment]
Alpha by first name would be great, thanks. 

And yes, identifying the team leads on the teams page would be good. Thank you!

**Comment by maneesha** [comment]
Fixed with #1092
