### ISSUE TITLE
Cannot filter incubator lesson

### ISSUE THREAD

**Issue by annajiat** [carpentries/carpentries.org-archive#1088]
At 
Browse Community Developed Lessons
https://carpentries.org/community-lessons/#the-carpentries-incubator

I could not find any way to see only the alpha stage lessons but not pre-alpha lessons
As "alpha" is a substring of "pre-alpha", both of them show up.

How do we filter to see only alpha but not pre-alpha?

As a workaround, I used sorting which helped. Thanks for that.

**Comment by fmichonneau** [comment]
Thanks for the feedback @annajiat!

We are looking to improve the usability of this page in the future. 

For the time being, your workaround is the best way to see the lessons in the "alpha" stage of development.

**Comment by fmichonneau** [comment]
Notes:
- category filtering can be implemented on the JS side: https://react-table.tanstack.com/docs/examples/filtering
- but there is no easy way to do this directly in R yet: https://github.com/glin/reactable/issues/9

**Comment by maneesha** [comment]
Closing this as we are moving to a new website.  We will [consider search/filter options](https://github.com/carpentries/carpentries-hugo-theme/issues/53) on tables in our new site at a later date.
