### ISSUE TITLE
'Connect' page

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#109]
Related to https://github.com/carpentries/carpentries.org/pull/108, we could add a 'Connect' page with an overview of how to connect with us, like the 'Learn' and 'Teach' pages, and also put a link to Slack in there and a link to the 'Join Us' page for more information on specific things.

**Comment by fmichonneau** [comment]
that sounds good. I'll work on this. We'll need to check for the overlap with "Join Us".

**Comment by tracykteal** [comment]
Right, I think we mainly link to 'Join Us' for more specific information. 

Teach and Learn are both relatively short.

**Comment by fmichonneau** [comment]
I started a backbone in #109. Once it's merged, we can flesh out the exact wording/content of this "Connect" page.

**Comment by weaverbel** [comment]
@fmichonneau @tracykteal there is also some of that info on `About`. It would be good to decide where it best sits and then consolidate it.

**Comment by tracykteal** [comment]
I took some of the things out of Connect and added a little intro text in #116

**Comment by weaverbel** [comment]
Can we close this now? PR has been merged.

**Comment by jduckles** [comment]
Closing, PR was merged.
