### ISSUE TITLE
Teach --> Instructor Training

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#11]
Should this go to [the instructor training curriculum](http://carpentries.github.io/instructor-training/) or to the documentation about instructor training in the [handbook](https://docs.carpentries.org/topic_folders/instructor_training/index.html)?

**Comment by weaverbel** [comment]
I can do either - handbook first?

**Comment by ErinBecker** [comment]
Closing. This has been resolved by changing the menu item to "Become an Instructor" and adding https://carpentries.org/become-instructor/
