### ISSUE TITLE
Presence of Library Carpentry on this website?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#112]
What is LC's presence going to be on the Carpentries website?
Other than the blog post about Chris's hire I do not see any mention of LC on this site.

**Comment by weaverbel** [comment]
I will leave this for @tracykteal to decide. I am happy to say something about LC, but am not sure what Tracy and the Exec Council's official line is.

**Comment by tracykteal** [comment]
There hasn't been official motions from either side about a formal relationship. It's under discussion now, so we'll hold off on including it for now.

**Comment by weaverbel** [comment]
I will close this as we will have a determination on the content after the two committees meet and approve formal motions.
