### ISSUE TITLE
Update wedidit links 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1150]
Update wedidit links to new fundraising platform: http://give.communityin.org/TheCarpentries

**Comment by maneesha** [comment]
PR #1153 fixes this for the carpentries.org website. 

Keeping this open because I need to check on

- [x] any donation links in the three lesson program site
- [x] any donation links in the handbook
- [ ] GitHub sponsors (tagging @fmichonneau  on this one)

**Comment by maneesha** [comment]
Tagging @acrall FYI

**Comment by maneesha** [comment]
Lesson programs - all sites redirect to carpentries.org
Handbook - fixed with https://github.com/carpentries/docs.carpentries.org/pull/753 

@fmichonneau  do we need to do anything with GitHub sponsors?

**Comment by fmichonneau** [comment]
Yes, we are going to need to update the links across our lessons. I've put this on our curriculum team agenda.

**Comment by maneesha** [comment]
Thanks @fmichonneau 
Do you want to keep this issue open here?

**Comment by fmichonneau** [comment]
I took care of this on Friday across all our lessons.
