### ISSUE TITLE
Should we remove inactive communities from "volunteer" page? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1185]
On the [volunteer page](https://carpentries.org/volunteer/) we see large boxes representing various segments of our community.

This includes inactive groups like Assessment, Champions, Lesson Infrastructure.  They are all listed as inactive on our [community page](https://carpentries.org/community/).  Should we consider removing them from the big boxes in the volunteer page? 

Tagging @kmomar  @acrall  for feedback.

**Comment by kmomar** [comment]
@maneesha Can we remove the Assessment, Champions, and Lesson Infrastructure boxes? I'm not sure how to do this myself.

**Comment by maneesha** [comment]
Fixed with #1220
