### ISSUE TITLE
Keeping external Carpentries related resources in sync with current systems

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1188]
On our [Development of Lessons page](https://carpentries.org/community/) we link to an [external tutorial on contributing via GitHub](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md).  It is not in sync with our current systems.  It's not an entirely external resource as it is directly about Carpentries work. 

- The guide asks people to email checkout@carpentries.org. We have recently changed this email to instructor.training@carpentries.org.  We are currently in the process of updating our own references to that email address, but we would not necessarily know to update things here.  Also, that is intended just for people who are submitting an issue as part of instructor training checkout, and not for general contributions.
- The guide says that `gh-pages` is the default branch for all Carpentries lesson repos.  This is not the case.
- The guide identifies features like menu options by color.  Given GH offers light/dark modes, the colors may not show the same for all users.
- Screenshots are generally out of date due to changes in GitHub's interface in the past few years.

Tagging curriculum team members here for feedback.  @carpentries/core-team-curriculum

**Comment by karenword** [comment]
I will add that we also link to this from our Instructor Training curriculum. In the [most recent update](https://data-lessons.github.io/instructor-training/checkout/index.html), after reviewing how to post to issues, we say: "If you find something that you know how to fix by changing the code of the lesson, you may instead wish to submit a Pull Request (PR). You can also view and comment on existing PRs. We will not cover the details of how to create a PR, but there is a community-[contributed guide](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md) that can help."

Would love to have an alternative resource for this reference as well!

**Comment by maneesha** [comment]
Pinging @carpentries/core-team-curriculum for feedback.  Could we consider making this guide our own so we can ensure it stays up to date?

**Comment by zkamvar** [comment]
I'll put this on our team meeting agenda for this week.

**Comment by karenword** [comment]
Related: at a recent Trainer meeting it was suggested that [this resource developed for a CarpentryConnect event in Australia](https://github.com/DamienIrving/teaching/blob/master/carpentries_connect_2021.md) would be a good guide for lesson contributions. On the one hand, community-created resources have maintenance challenges like those noted here. On the other hand, they are a valuable way to recognize community effort and highlight relationships between local and global communities. (Also they tend to fulfill needs currently unmet by our own documentation, as is the case here).

**Comment by maneesha** [comment]
Checking in to see if @carpentries/core-team-curriculum has any updates.

**Comment by fmichonneau** [comment]
I contacted the authors on Nov 18 but haven't heard back. I plan to ping them again mid-January.

**Comment by MCMaurer** [comment]
I'm sorry for not updating here sooner, but I did get in contact with Dana this week and got the thumbs up to transfer the repository. I responded with instructions for transferring the repository, I will update here once that process is completed.

**Comment by fmichonneau** [comment]
The authors of the tutorial transferred their repository to the carpentries incubator: https://github.com/carpentries-incubator/swc_github_flow

**Comment by maneesha** [comment]
Now that we own the repo, will the Curriculum Team @carpentries/core-team-curriculum be updating this given the points noted above?

**Comment by tobyhodges** [comment]
The Curriculum Team has taken care of the most pressing points you mentioned above, and we have created issues for the others, adding the `help-wanted` label in the hope that someone will help us further improve the resource. I've added the repository to [the Help Wanted Issues listing](https://carpentries.org/help-wanted-issues) to further help with this.

I'm going to close this issue now.
