### ISSUE TITLE
Update information on CarpentryCon task force

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1189]
The [CarpentryCon task force](https://carpentries.org/carp-con-tf/) page is out of date.  It refers to us planning CC2020 and that we will be planning CC2021.  

Tagging @acrall  for review.

**Comment by maneesha** [comment]
Also at the top of [the community page](https://carpentries.org/community/) it says CarpentryCon is "our annual in-person meetup for our global community."  When you click through and go down that page to the [CarpentryCon section](https://carpentries.org/community/#carpentrycon), it says "A global CarpentryCon will be held every two years."

**Comment by maneesha** [comment]
Hi @acrall I wanted to bump this up especially as we just announced plans for CarpentryCon 2022.  Let me know how I can help.

**Comment by acrall** [comment]
@kmomar and I met to discuss this. I'm checking in with @ErinBecker about any procedures for archiving past service on a task force, etc.

**Comment by maneesha** [comment]
Thanks @acrall  -- we want to archive information as appropriate.
We also want to make sure current information is up to date. This is not just about past task force members.  We should also make sure current information about CarpentryCon is up to date, especially as we've just announced plans for 2022.

**Comment by ErinBecker** [comment]
Thanks for looping me in @acrall. I agree that the most urgent piece here is making sure the information on this page is accurate for CarpentryCon 2022.

We don't currently have any processes for archiving past task force membership.

**Comment by acrall** [comment]
@maneesha I put in a pull request [here](https://github.com/carpentries/carpentries.org/pull/1227)

**Comment by maneesha** [comment]
Fixed for now with #1227
We should be sure to update this page as planning CC2022 continues.
