### ISSUE TITLE
List past community discussions on website?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1191]
We have a page for [community discussions](https://carpentries.org/community_discussions/).  This includes a list of past calls - seems to be just ones with special topics, not regular discussion sessions.  The last one listed is from December 2019. Is this a list we want to keep up to date? If so we should add in all the calls from 2020 and 2021.  If not, I would recommend removing this list so that it doesn't look like we have been inactive fro the past two years.

Tagging @acrall  for feedback.

**Comment by maneesha** [comment]
Also, looking at the list again, I'd also want to consider why we're listing these topics.  Some of them have links to notes, videos, slides, etc. but many do not.  So for example in 2018, Anelda ran a session on How to run a workshop with no money.  That would be really interesting to a lot of our community members, but we have no record of what was actually discussed there.  

So would this list be a general account of sessions we've run, or a source of information if you weren't at the session itself?

**Comment by acrall** [comment]
@maneesha This was discussed by the CDT at today's meeting and we have decided to remove. I will put in a pull request

**Comment by acrall** [comment]
Closing this issue since the content has been removed.
