### ISSUE TITLE
Update information on Lesson Infrastructure Task force

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1194]
The lesson infrastructure task force has [its own page description](https://carpentries.org/lesson-infra/). 
It is linked to from several other pages:

* [Committees and task force page](https://carpentries.org/committees/)
* [Community overview page](https://carpentries.org/community/#lesson-infrastructure) *listed here as inactive*
* [Volunteer page](https://carpentries.org/volunteer/) 

Should it be listed as inactive in its own page and on the committees page?
(Note there is a [separate issue](https://github.com/carpentries/carpentries.org/issues/1185) as there are several inactive communities listed on the volunteer page) 

Tagging Curriculum Team @carpentries/core-team-curriculum

**Comment by zkamvar** [comment]
> Should it be listed as inactive in its own page and on the committees page?

Yes. As I am in the process of doing a retrospective of the committee, I think the messaging should be something like (but could be changed):

> The Lesson Infrastructure Committee went into hiatus in March 2020 due to the pandemic. We are in the process of performing a retrospective of this committee to identify strengths and areas of improvement. These findings will help us guide the formation of the next committee to ensure that it aligns with our core values. For information on this effort, please contact Zhian Kamvar or François Michonneau.

**Comment by maneesha** [comment]
Closed with #1207
