### ISSUE TITLE
Add podcast release dates 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1195]
It's great to see our [podcasts listed on our website](https://carpentries.org/podcasts/)! Could we add in release dates for each episode to the description?

**Comment by maneesha** [comment]
Pinging @kmomar

**Comment by maneesha** [comment]
Hey @kmomar  if you can list the release dates here, I can take care of a PR.

**Comment by kmomar** [comment]
Hi @maneesha sorry about the delay! I'll look for the release dates and add them

**Comment by kmomar** [comment]
@maneesha I'm sorry for the endless delay on this. The only way I can think to find these is to look through all our tweets for when we posted these and it's been on the backburner for a while now. I promise I have not forgotten

**Comment by maneesha** [comment]
No worries - not super high priority.

**Comment by maneesha** [comment]
I started to dig through tweets to see what we can find.

[Fireside Chats is called Episode 1 on Twitter](https://twitter.com/thecarpentries/status/1371513694685949952), was tweeted on March 15 2021.

[Equity and Inclusion is called Episode 2 on Twitter](https://twitter.com/thecarpentries/status/1375511333836222466) and was tweeted on March 20 2021.

[Community Building online is called Episode 3 on Twitter](https://twitter.com/thecarpentries/status/1379865082465771526) was tweeted on April 7 2021.

@kmomar  I can add in these dates. I would also recommend sorting from most recent to oldest (rather than the way it is now).  Let me know how that sounds to you.
