### ISSUE TITLE
Frequency of community discussion sessions

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1197]
The [community discussion page](https://carpentries.org/community_discussions/) notes that pre/post discussions are twice a week and that themed discussions and conversations are once a month.  How should we rephrase this given we are not running sessions on a set frequency like this? Should we remove the references to the frequency entirely? 

Tagging @acrall  @kmomar

**Comment by kmomar** [comment]
For now, We are going to remove the references to the frequency.
