### ISSUE TITLE
drop down nav menus are over-populated - WIP

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#12]
There are an awful lot of items in many of the drop down nav menus. This makes for a very crowded and overwhelming feel.

I recommend the following for the About menu: 

## About
- About Us
- Code of Conduct
- Governance
- Policies

(Unless there is a legal requirement that we make "Privacy Policy" it's own category, I would recommend letting it stand within the Policies category.)

Will add to this issue for the other menus.

**Comment by weaverbel** [comment]
Happy to remove Privacy as it is now in the footer

**Comment by ErinBecker** [comment]
Closing this as the menu lists are much smaller now (no more than 5).
