### ISSUE TITLE
Link to Bonus Module in online workshop recommendations

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1201]
The [Online workshop recommendations](https://carpentries.org/online-workshop-recommendations/) page notes:

> We will soon be piloting a short workshop to support instructors in transitioning online.

Can we update this to directly refer to our online teaching bonus modules, or was this referring to something else? 
Tagging @klbarnes20  for feedback.

**Comment by maneesha** [comment]
Pinging @klbarnes20

**Comment by klbarnes20** [comment]
Sorry for missing this. I added some text and requested you and Karen review: #1243

**Comment by maneesha** [comment]
Fixed with #1243
