### ISSUE TITLE
Contact person for Mentee/Mentor applications

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1210]
In the [Instructor Development/Mentoring Groups](https://carpentries.org/community/#instructor-development) section of the Community page, we have links to Mentee and Mentor applications.  The applications are currently closed, but refer to an external community member as the key contact. Should this be changed to have a Core Team contact?

**Comment by maneesha** [comment]
Pinging @acrall

**Comment by maneesha** [comment]
Hi @acrall  Are you managing the mentoring program?

**Comment by acrall** [comment]
@maneesha Many apologies for such a long delay with this. I was trying to get some additional information. Let's change the contact to community@carpentries.org for now. I still need to figure a few things out with this but that will give the community a point of contact until we determine next steps. Thanks!

**Comment by acrall** [comment]
@maneesha Many apologies for such a long delay with this. I was trying to get some additional information. I saw you changed it to my email address, so thank you. Closing this issue

**Comment by maneesha** [comment]
Re-opening this @acrall  as this was referring to the application forms which still refer to a community member and are out of date.  This should be resolved.

**Comment by maneesha** [comment]
Checking in @acrall

**Comment by acrall** [comment]
Opened a [pull request](https://github.com/carpentries/carpentries.org/pull/1305) that will hopefully resolve this issue. Sorry for the misunderstanding

**Comment by maneesha** [comment]
Thanks Alycia! Fixed with #1305
