### ISSUE TITLE
Update Maintainer Application 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1213]
On the [Maintainers section of the Community page](https://carpentries.org/community/#maintainers), there is a link to "Apply to become a Maintainer" that is out of date.   It says applications closed April 2020 and we hope to reopen later that year.  Do we have a new form to link to? 

tagging @carpentries/core-team-curriculum

**Comment by maneesha** [comment]
Pinging @ErinBecker

**Comment by maneesha** [comment]
If anyone on @carpentries/core-team-curriculum can share what should go here, I can put in a PR.

**Comment by ErinBecker** [comment]
Thank you @maneesha! We will not have a continuously open application for this, but will open applications at particular times. This program functions much more like the Trainer Training program than like Instructor Training. Could you please put in a PR to note that upcoming rounds of Maintainer Onboarding will be announced on our blog and newsletter?
