### ISSUE TITLE
Masterlist of redirects needed 

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#129]
Redirects:  

| Status | From | To | 
|------- | ---- | ---- | 
| 110cd18e    |  https://software-carpentry.org/CoC-enforcement/     |     https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#enforcement-manual   |
| 7470393c | https://software-carpentry.org/CoC-reporting | https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#reporting-guidelines | 
|   | https://docs.carpentries.org/topic_folders/policies/CoC-enforcement.html |  https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#enforcement-manual | 
|    | https://docs.carpentries.org/topic_folders/policies/CoC-reporting.html | https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#reporting-guidelines | 
| 3ef8b4cc | http://www.datacarpentry.org/partnerships/ | https://carpentries.org/membership/ | 
| c8a99e41 | https://software-carpentry.org/scf/partners/ | https://carpentries.org/members/ | 
| 808bf3ce | https://software-carpentry.org/membership/ | https://carpentries.org/membership/ |
| d3c8dadd | https://software-carpentry.org/privacy/  | https://docs.carpentries.org/topic_folders/policies/privacy.html |
| 08923dd3 | https://software-carpentry.org/workshops/operations/ | https://docs.carpentries.org/topic_folders/hosts_instructors/index.html  |
| (already done) | http://www.datacarpentry.org/checklists/ | https://docs.carpentries.org/topic_folders/hosts_instructors/index.html |
| fd3b139b | https://software-carpentry.org/join/ | https://carpentries.org/join/  |
| fe4e798f | http://www.datacarpentry.org/involved-instructor/  | https://carpentries.org/become-instructor/  |
| 3e76b37e | https://software-carpentry.org/join/donate/ | https://carpentries.org/donate/ |
| b16cfd9b | http://www.datacarpentry.org/involved-donate/  | https://carpentries.org/donate/ |
| cbba8c50 | http://www.datacarpentry.org/people/ | https://carpentries.org/team/  | 
| 0af1ca07 | https://software-carpentry.org/join/subcom_and_tf/ | https://carpentries.org/community/  | 
| e626cfc8 | http://www.datacarpentry.org/governance/  | http://carpentries.org/governance/  | 
| f6da04c3 | https://software-carpentry.org/scf/  | http://carpentries.org/governance/  |
| b8c76a44 | http://www.datacarpentry.org/newsletter/ | https://carpentries.org/newsletter/  | 
| dbca740a | http://www.datacarpentry.org/self-org-lead/ | https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist  | 
| 01758984 | http://www.datacarpentry.org/email-templates/ | http://docs.carpentries.org/topic_folders/workshop_administration/email_templates.html | 
| ff015570 | http://www.datacarpentry.org/mentoring/  | https://docs.carpentries.org/topic_folders/mentoring/index.html   | 
| e208a600 | http://www.datacarpentry.org/assessment/  | https://carpentries.org/assessment/  |
| 546a8b7c | https://software-carpentry.org/assessment/  | https://carpentries.org/assessment/  | 

Content to remove: 
 -  [x] Retire the “Help Wanted” page (https://software-carpentry.org/join/help/)
- [x] Retire the Discussion Forum (http://discuss.datacarpentry.org/)

Other: 
- [x] Add section for community service awards to website
    - [x] Add redirect from https://software-carpentry.org/scf/awards/ 
    - [x] Add awards from 2017
- [x] Move content on self-organized workshops to handbook
      - http://www.datacarpentry.org/self-organized-workshops/ 
- [ ] Move content on centrally organized workshops to handbook
      - http://www.datacarpentry.org/workshops-host/ 
- [x] Rename https://software-carpentry.org/team/ so that title is “Our Instructors”
- [x] Add "Reading material" section to website and add redirects from:
   - [x] SWC https://software-carpentry.org/reading/
    - [x] DC http://www.datacarpentry.org/media/ 
- [x] Add "Jobs" section to website and add redirects from:
   - [x] http://www.datacarpentry.org/jobs/ 
- [x] Migrate content from http://www.datacarpentry.org/troubleshooting/ to handbook and add redirect
- [x] Migrate content from http://www.datacarpentry.org/checkout/ to handbook and add redirect

**Comment by ErinBecker** [comment]
The list above covers all page level (not content level) clean up and reorganization needed for the SWC and DC websites to move shared content to either the Carpentries.org website or to the handbook.

**Comment by ErinBecker** [comment]
@fmichonneau will be working on this list on Friday April 27th.

**Comment by fmichonneau** [comment]
I completed the redirects for the SWC and DC websites listed in the tables.

As far as I could tell, there is no way to set up redirects in Sphinx (https://github.com/carpentries/handbook/issues/205) so I couldn't setup the redirects within the docs.

**Comment by weaverbel** [comment]
Can this be closed now @ErinBecker @fmichonneau ?

**Comment by ErinBecker** [comment]
This isn't ready to close yet. The redirect from the table are complete, but there are still a number of un-checked items in the to-do list.

**Comment by weaverbel** [comment]
I have created a Community Service Awards page but we need to get this approved by the new Executive Council. I will contact them for review and also will not link this page from any menu until they have approved it. https://github.com/carpentries/carpentries.org/blob/gh-pages/pages/community-service-awards.md

**Comment by maneesha** [comment]
Are there any redirects that still need fixing?
@ErinBecker @fmichonneau

**Comment by fmichonneau** [comment]
As far as I know, my comment from April 27 and Erin's from June 21 are still valid.

**Comment by maneesha** [comment]
Checking off "Retire the “Help Wanted” page (https://software-carpentry.org/join/help/)" as it will be addressed in the [SWC repo](https://github.com/swcarpentry/website/issues/1070)

**Comment by maneesha** [comment]
Creating a [new issue](https://github.com/carpentries/carpentries.org/issues/384) for 

>  Add "Reading material" section to website and add redirects from:
>  SWC https://software-carpentry.org/reading/
>  DC http://www.datacarpentry.org/media/

to allow for more discussion there.  Checking them off here,

**Comment by maneesha** [comment]
@fmichonneau Could we make the following redirects:

- https://software-carpentry.org/scf/awards/  to https://carpentries.org/awards/
- https://datacarpentry.org/checkout/ to https://carpentries.github.io/instructor-training/checkout/
- http://www.datacarpentry.org/troubleshooting/  to https://docs.carpentries.org/topic_folders/hosts_instructors/instructor_tips.html

(Or if you can show me how redirects work I can do this myself)

**Comment by maneesha** [comment]
Awards page redirect fixed with https://github.com/swcarpentry/website/commit/492b2f65f45de1283cdf23138a76651676877a9f

**Comment by maneesha** [comment]
Data Carpentry checkout page fixed with https://github.com/datacarpentry/datacarpentry.github.io/commit/7eeedd9d3f8c01b50a31a16b5196756cdd29a9a0

**Comment by maneesha** [comment]
Data Carpentry troubleshooting page fixed with https://github.com/datacarpentry/datacarpentry.github.io/commit/ce3d3aa31741958544ef90b5e7f8cc9ffd8a2968
