### ISSUE TITLE
Supporters Page outdated

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#1292]
The [Supporters](https://carpentries.org/supporters/) page needs to be updated with information including our current grants. Before updating I'd like to know the plans for this page for the new website and whether this page will be included.

**Comment by maneesha** [comment]
Bump @Talishask

**Comment by Talishask** [comment]
Thanks @maneesha . I have this on my list of things and will work with Kari on how it fits in the list of priorities.

**Comment by kariljordan** [comment]
@Talishask we are working on a guide for the community to use when collaborating with The Carpentries on grants. The guide will be published 1 February and will include a link to our supporters page. Having this page updated by the end of January would be fantastic. I can't imagine it taking that long, and I'm happy to submit the PR myself if needed.

**Comment by maneesha** [comment]
@Talishask  @kariljordan  However you want to handle it is fine.  If I have all the info, I'm happy to do this.  If it's easier for one of you to do it directly, that works too.

**Comment by kariljordan** [comment]
PR is in!  #1299

**Comment by maneesha** [comment]
Fixed with #1299
