### ISSUE TITLE
Banner as image

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#131]
Rather than having the banner on the home page be a logo and a slogan, we can incorporate the slogan into the logo, and just used that updated logo so we can control text layout and font.

@lexnederbragt commented about the break point in the slogan text.

**Comment by fmichonneau** [comment]
Some issues with using image-based approach are:

- lower accessibility
- not good for SEO
- will not work well on mobile devices

We may want to remove the "welcome to the carpentries" part to avoid the multi-paragraph slogan though.

**Comment by tracykteal** [comment]
Thanks, those are important points, and I agree means we probably shouldn't make that change. Maybe just removing the 'Welcome to The Carpentries' will help resolve. We could potentially also address the font in the css.

**Comment by weaverbel** [comment]
I have removed "Welcome to the Carpentries!" from site slogan.

**Comment by fmichonneau** [comment]
@lexnederbragt Is removing the "welcome to the carpentries" sentence addressed your concern about the breakpoint. Did you notice something else?

**Comment by lexnederbragt** [comment]
No, all good. Thanks!

**Comment by fmichonneau** [comment]
Closing. Follow up in https://github.com/carpentries/carpentries.org/pull/141
