### ISSUE TITLE
What we do

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#132]
From @lexnederbragt in another repo

"
Under "What we do" on the front page it says

>The Carpentries teach foundational computational, coding, and data science skills to researchers >worldwide. Software and Data Carpentry workshops are based on our lessons. 

This will for new visitors be the first time they see "Software and Data Carpentry workshops" so I propose

> Software Carpentry and Data Carpentry workshops are based on our lessons.
"

**Comment by weaverbel** [comment]
Fixed
