### ISSUE TITLE
Add welcome sessions to community discussions overview page

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1329]
The [Community Discussions page](https://carpentries.org/community_discussions/) lists three types of community discussions. 
@acrall  Should we add welcome sessions to this page? 

Feel free to put in a PR or share the information in this issue and I'll take care if it.

**Comment by maneesha** [comment]
Checking in @acrall

**Comment by acrall** [comment]
@maneesha I consider the Welcome Sessions as themed community discussions but I will bring this up with the CDT at our next meeting to discuss

**Comment by acrall** [comment]
@maneesha We discussed this at today's meeting and decided that we do not want to list it separately but consider it a themed community discussion. Thanks!
