### ISSUE TITLE
Typeform for blog posts?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1338]
At the bottom of the [join page](https://carpentries.org/join/) there is a link to Typeform to submit a blog post.  It refers to the Software Carpentry and Data Carpentry blogs, so I'm guessing this isn't being used.  @kmomar  would you like to remove this or replace it with something else? 

@kmomar  Feel free to respond here and I'll make the change - or if you'd like, you're welcome to put in a PR yourself!

**Comment by kmomar** [comment]
@maneesha let's remove that link

**Comment by maneesha** [comment]
Fixed with #1342
