### ISSUE TITLE
Link to sponsorship page?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1339]
The [join page](https://carpentries.org/join/) says to get in touch if interested in becoming a sponsoring organisation.  Instead, should it link to the [sponsorship](https://carpentries.org/sponsorship/) page? 

@kmomar  Feel free to respond here and I'll make the change - or if you'd like, you're welcome to put in a PR yourself!

**Comment by kmomar** [comment]
@maneesha I think we should change the call to action to learn more on the sponsorship page as you are suggesting.

**Comment by maneesha** [comment]
Fixed with #1342
