### ISSUE TITLE
Direct users to CarpentryCon websites

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1340]
On the [Carpentry Con page](https://carpentries.org/carp-con-tf/) we have a lot of information that duplicates what is on the CarpentryCon websites. I'd like to re-organize this page so it only includes summary information, and links to each year's CarpentryCon website for more information about task force members and other information.  This will help us avoid repetitive and potentially erroneous information.  

@acrall  Please let me know if you have any concerns with this.

**Comment by maneesha** [comment]
Checking in @acrall

**Comment by acrall** [comment]
@maneesha, I think this is a great idea. I'm having issues finding the edits you made via #1355 but will check in with you via Slack
