### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#136]
Carli Spina gave us some great feedback on accessibility. Her comments are here. I'll work to break these into individual issues, but wanted to capture them here.

1. [X] There doesn't seem to be any alt-text for the image in the masthead. It is decorative, so you couple probably use blank alt-text to indicate that, but without any, it could cause issues for some screen readers/assistive devices.
  FM: Done in e7f18ddbcf0787336453ec30af2bed84e6878ffa. It's a little weird given that it's handled by javascript. According to the documentation, using [blank alt text is already the default](https://github.com/jquery-backstretch/jquery-backstretch#image-definition). 

2. [x] At several points, you links/buttons labelled with just "more" or "here". For someone navigating directly to links (for example, with a screen reader), this can be confusing and difficult to use. The better practice is to have the link text indicate where the link will take you.

3. [X] The white on blue/blue on white text is showing up as a bit low contrast. I've definitely seen worse, but it is showing up as failing the the contrast test when I run it through the WebAIM contrast tool.
  FM: Done in 047053e. Using a slightly darker blue to pass the test.

4. [X] The search in the Carpentries Handbook is missing the necessary form label.
  FM: Done in 07b53b6.

5. [x] In the Carpentries Handbook, the grey on darker grey text (for example the heading "General Resources" and the subsections under each of the headings once you click on them.

6. [X] On the Testimonials page, the use of italics will make it tougher for some people to read the text and the font size of the attribution line for each testimonial is too small.
  NOW FIXED - Belinda

7. [ ] Some pages (in particular About and Testimonials) would benefit from having less text and more white space to make them more universally designed, for both those with visual impairments or cognitive disabilities, those for whom English is not their first language, and those who are rushed/distracted.

8. [x] On the lessons page, it generally isn't a best practice to use tables for style instead of to convey tabular information (this also applies to the Become a Member Organization page, the Our Trainers page, and the Our Maintainers page). These tables aren't too problematic, but where the tables include icons without descriptive text for the links, it will be difficult to navigate through the content using a screen reader.

9. [x] In the form to request information, some of the options do not seem to be properly enclosed in the fieldset. Also, the use of Captcha will be problematic for those using some assistive devices and those with some types of disabilities.

10. [ ] You might want to set the language for the sections of the site in Spanish to Spanish (lang="es") so that assistive devices will read that content correctly.

11. [x] The Our Members page is a bit difficult to read because of how the logos are interspersed with the text. Also, the alt-text for the logos should probably be blank since they are decorative. Right now the alt-text is being interpreted as redundant.

12. [x] On the Our Team page, you seemed to have skipped the first heading level (h1).

**Comment by weaverbel** [comment]
I have fixed item 6.

**Comment by fmichonneau** [comment]
I updated this issue to make it a checklist. I addressed a few of these comments and fixed a couple of bugs in the template that were creating empty links that could confuse screen readers (see https://github.com/carpentries/carpentries.org/pull/145 for full details)

**Comment by fmichonneau** [comment]
@katrinleinweber given all your work on fixing the "here" and "more" on our lessons, would you be willing to check the main carpentries.org website as well?

**Comment by maneesha** [comment]
Assigning to @kariljordan  to consider as part of the The Carpentries Equity, Inclusion, and Accessibility Roadmap

**Comment by maneesha** [comment]
@serahrono  I know you're doing a lot of work around accessibility. Is this something you want to keep open?

**Comment by maneesha** [comment]
Last bullet - we do have `h1` header built by the template:

`<h1>The Carpentries Core Team</h1>`

**Comment by maneesha** [comment]
Bullet about our members - checking this off because we don't have logos on this page so this likely refers to an old version.  Also we are re-doing this page to automatically build from AMY now that we have member status in AMY.

**Comment by maneesha** [comment]
Bullet about the form to request information - checking this off as we don't have such a form.

**Comment by maneesha** [comment]
Bullet about gray on gray text in handbook - moving this to the handbook repo  

See https://github.com/carpentries/docs.carpentries.org/issues/749

**Comment by maneesha** [comment]
Bullet about text-heavy About and Testimonials pages - Testimonials page has been updated to just show excerpts, with click through for full text.  About page is still very text heavy.  @kmomar  @acrall  is this something we have plans to address?

**Comment by maneesha** [comment]
Second bullet about more/here links is addressed with https://github.com/carpentries/carpentries.org/pull/1147

**Comment by maneesha** [comment]
For the  bullet about tables - our tables on the lessons pages all now include alt text for the images.

**Comment by maneesha** [comment]
For the bullet about content in Spanish - the content on carpentries.org and the three lesson program sites is all in English.  We do have lessons in other languages.  Tagging @fmichonneau @tobyhodges @zkamvar  to ask where the best place to move this issue would be.  Thanks!

**Comment by kmomar** [comment]
@maneesha @acrall In reference to the about page, Alycia and I are considering something similar to the testimonials page change where there are dropdowns rather than hyperlinks to the section. Would this be a good path forward?

**Comment by maneesha** [comment]
As we will be working with an accessiblity specialist and are doing a full redesign of our website, I'd like to close this since I think it will be mostly irrelevant.  @fmichonneau  is that OK?
