### ISSUE TITLE
The Instructors Map page is displaying a google map development only error

### ISSUE THREAD

**Issue by karlbenedict** [carpentries/carpentries.org-archive#1374]
The Instructors Map page (https://carpentries.org/instructors-map/) is showing the Google Maps error that in my experience has been associated with a Google Maps API key associated with an account that hasn't connected a credit card with the account. Several years ago Google changed their API use policy to require that all accounts, even those operating within the free usage tier, link a credit card to their account. 

<img width="1010" alt="2022-04-25_18-57-12" src="https://user-images.githubusercontent.com/1638410/165156046-5d9e4503-a22b-4093-a1e6-41e53179f600.png">

**Comment by fmichonneau** [comment]
thanks for pointing this out! It should now be fixed.
