### ISSUE TITLE
Issues with Slack links on welcome tip sheet

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#1378]
During the community welcome session I led today we went through the [welcome tip sheet](https://carpentries.org/welcome-tip-sheet/). When the participants clicked to join the various Slack channels the link led them to this page: 

https://swcarpentry.slack.com/

This page requires that you sign in to Slack. If you have never joined our Slack organisation, you actually need to visit this page:

https://swc-slack-invite.herokuapp.com/

I'm wondering how we can improve the links or make it clear that you have to be a part of the Slack organisation **first** before you can join the various Slack channels.

**Comment by maneesha** [comment]
Fixed with #1379
