### ISSUE TITLE
Footnote anchors do not scroll into view in blog

### ISSUE THREAD

**Issue by zkamvar** [carpentries/carpentries.org-archive#1398]
If footnotes are included in a blog post and someone attempts to scroll to the footnote or the footnote reference, the page will scroll past the footnote (see #1396 and https://carpentries.org/blog/2022/05/workbench-beta/#fnref:1). I know this is due to the height of the title bar, but I'm not sure how to fix this particular situation in CSS.

**Comment by annajiat** [comment]
@rahman9909
Please see if you can help.

**Comment by maneesha** [comment]
I am leaving this open in case anyone can fix this easily, but do not want to put much time into it as we may be redesigning our website entirely so this may become irrelevant.

Note this happens on a lot of the templates we use - for example, go here https://datacarpentry.org/lessons/ and click on any of the curriculum headings, and the title bar overlaps the heading.

**Comment by maneesha** [comment]
Closing this as not relevant to as we move to a new website.
