### ISSUE TITLE
interactive elements from files.carpentries.org do not display in Chrome or Opera

### ISSUE THREAD

**Issue by zkamvar** [carpentries/carpentries.org-archive#1429]
The [help wanted issues page](https://carpentries.org/help-wanted-issues/) does not display in Chrome or Opera browsers due to the same error as https://github.com/carpentries/carpentries.org/pull/1425:

```
Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': 
    This document requires 'TrustedHTML' assignment.
```

The help wanted feed comes from the `get-remote` rule in the makefile: https://github.com/carpentries/carpentries.org/blob/d55148ab47261e25cf3634cc169bc4531a1a3df2/Makefile#L7-L11, which creates a JSON object that has HTML and JS code embedded that the scripts in the headers act on. I'm not sure what can be done with this since it's not a script that we control ourselves.

**Comment by fmichonneau** [comment]
I think these issues are coming from trying to improve our https score by tightening our security policy around external content. See [this asana task](https://app.asana.com/0/1201014068954724/1201044632853493/f)

**Comment by fmichonneau** [comment]
I updated the policy and dropped the trusted origin requirement, things render on Chromium for me now. Could you please confirm?

**Comment by zkamvar** [comment]
Confirmed
