### ISSUE TITLE
Take down CarpentryCon banner (TO DO IN AUGUST)

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1438]
Opening this issue as a reminder to take down the CarpenryCon banner on our front page.  At the same time, we should remove the text on the [calendar section](https://carpentries.org/community/#community-events) about CarpentryCon.  

@acrall  would you like to have this taken down as soon as CarpentryCon is over, or should we leave it up for a while?

**Comment by acrall** [comment]
Taking it down as soon as CarpentryCon is over will be great. Thanks for thinking of this!

**Comment by maneesha** [comment]
Completed with #1458
