### ISSUE TITLE
disqus is broken

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#144]
it is not getting loaded on blog posts

**Comment by weaverbel** [comment]
Is this fixed @fmichonneau ? Seems to be working for me.

**Comment by maneesha** [comment]
I see it on some but not all posts.  I don't see disqus on my [most recent post about programmatic assessment](https://carpentries.org/blog/2018/06/programmatic-assessment/) but I see it on several prior posts.

**Comment by fmichonneau** [comment]
yes, it's working OK now and can be closed.
@maneesha for now, `comments: true` needs to be added to the YAML header to get the comments. It's on my TODO list to enable it by default.
