### ISSUE TITLE
Core Team projects page out of date

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#1443]
https://carpentries.org/core-team-projects/ has a list of core team projects going through Q4 2021 as well as which people are on which team. The team members are very out of date. We could probably get rid of this page altogether?

**Comment by maneesha** [comment]
I think @kmomar  used to manage this page. I want to make sure he doesn't have any plans for it before taking it down.

**Comment by kmomar** [comment]
I would really like to phase this page out. It's hard for me to keep track of and ensure I'm updating it, and I don't think the community has responded to it the way we would like them to. It seems like this is mostly internal.

**Comment by ErinBecker** [comment]
I would be highly in favor of phasing out this page.

**Comment by maneesha** [comment]
PR #1449 removes the line from the Core Team page. The projects page still exists (anyone with the URL could get to it).  We could remove it entirely or consider part of all the clean up we'll do as we transition to the new site.

**Comment by ErinBecker** [comment]
Thank you @maneesha. I think removing the line from the Core Team page is perfect for now. We can worry about removing the content entirely as part of the transition to the new site.
