### ISSUE TITLE
missing some regional mailing lists

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#147]
This page: https://carpentries.org/community/ includes some of the regional mailing lists, but is missing the mailing lists for Davis, CA and Bay-Area (SF, CA). @jduckles, can you please add these?

**Comment by weaverbel** [comment]
Has this been done @jduckles ?If so, please close this issue.

**Comment by jduckles** [comment]
Can TopicBox be the canonical location for these? Otherwise we'll be perpetually out of sync.

**Comment by jduckles** [comment]
To be clear I'm proposing we remove the table of mailing lists at the bottom of the above linked page (leaving mailing list links in the various communities) and specifically mention for local-* connections to browse TopicBox.

**Comment by weaverbel** [comment]
That has now been done so I am closing this.
