### ISSUE TITLE
Memberships map not loading properly

### ISSUE THREAD

**Issue by ragamouf** [carpentries/carpentries.org-archive#1470]
Hello! I'm reluctant to do this while you're down a Director of IT, so my caveat is that this will be appreciated when you have bandwidth! 

The issue looks like not all memberships are loading on the map. For example, only 1 Australian membership is shown, UTS, when ARDC has a platinum membership. 

I would love to be able to use this map to show stakeholders the global community of The Carpentries! Many thanks

**Comment by maneesha** [comment]
Thanks for raising this @ragamouf 
I'll look into it this week.

**Comment by maneesha** [comment]
@ragamouf  We have fixed our queries so ARDC now shows on the map.  
I am opening a separate issue to address the map loading in development mode.
