### ISSUE TITLE
Update Governance page with newly appionted EC member

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#1496]
The [governance](https://carpentries.org/governance/) page of our website should be updated with the newly appointed EC member's information. Here's the information:

[Abdulai Imoro](https://www.linkedin.com/in/abdulai-imoro-9a739835/)
Appointed 2022
Country: Ghana

I will send Abdulai's photo via Slack.

**Comment by danielle06** [comment]
This will be Absulai's GitHub username name once verified: @aimoro
