### ISSUE TITLE
our team

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#15]
1) If the main heading is "our team" and that is being used to include all of the different groups listed in this nav header, then the "our team" section that lists staff should be changed to "our staff"

2) ["Our Instructors"](https://software-carpentry.org/scf/members/) assumedly has a list of Instructors in good standing with SWC. The title for this page is "Foundation Members", which is confusing. What is generating this list? Is this the list of members who were eligible to vote in the most recent elections? This page also has out-of-date references to the Steering Committee. 

3) The "Our Lesson Maintainers" and "Our Trainers" pages are nice in having a table of current members of those groups, however I don't like having the information about what all of our groups do split over a bunch of different pages, as that makes it difficult for a new community member to figure out how they want to get involved (they have to navigate to 15+ different pages to find all the information they need). I'm working on testing out the aesthetics for a more comprehensive "Join Us" page and will start another issue for that.

**Comment by weaverbel** [comment]
I can fix 1).
2) needs work - we need to generate this from AMY.
3) We need somewhere to list all these people. I created both these lists, and think they should stay here, but we can link off to the main info on a join page. Once it's live, we can remove content from here.

**Comment by weaverbel** [comment]
Have fixed team -> staff.
