### ISSUE TITLE
Include pronouns on Team page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#1542]
Our [Team page](https://carpentries.org/team/) does not include pronouns. I recommend adding pronouns. This page will then match up with our guidelines for Core Team email signatures.

**Comment by maneesha** [comment]
@carpentries/core-team Can each of you please respond here to note what you would like this to say?  Please note your text **exactly** as you would like it displayed. This is how it will look:

![image](https://user-images.githubusercontent.com/829690/207071457-5e0c5ebb-b0c1-44e7-9ca1-b69e84720c39.png)

**Comment by elletjies** [comment]
Any pronouns will do :)

**Comment by danielle06** [comment]
Pronouns: she/her/hers


Thanks, Maneesha!

**Comment by Talishask** [comment]
Any pronouns will do or Any pronouns are fine

**Comment by zkamvar** [comment]
Pronouns: he/him/his

**Comment by tobyhodges** [comment]
Pronouns: he/him/his

**Comment by brynnelliott** [comment]
Pronouns: she/her/hers

**Comment by acrall** [comment]
Pronouns: she/her/hers

**Comment by karenword** [comment]
she/her/hers

**Comment by kariljordan** [comment]
she/ella

**Comment by ErinBecker** [comment]
she/her/hers

**Comment by kmomar** [comment]
he/his

**Comment by klbarnes20** [comment]
she/her
