### ISSUE TITLE
Update Equity, Inclusion and Accessibility Page 

### ISSUE THREAD

**Issue by brynnelliott** [carpentries/carpentries.org-archive#1587]
The Carpentries Main page, in the About section, in the Equity, Inclusion, and Accessibility section: 

---
layout: page-fullwidth
title: "Equity, Inclusion, and Accessibility"
permalink:

---

## Accessibility Statement 

The Carpentries is committed to providing inclusive and accessible content that enables all individuals, including those with disabilities, to participate and engage fully. We are actively working to increase the accessibility and usability of Carpentries’ content and in doing so adhere to many of the available standards and guidelines including those from the World Wide Web Consortium. 

If there are any aspects of our community including the website, community discussions, instruction, or the design of our lessons that result in barriers to your inclusion, please [email us](mailto:team@carpentries.org) with as much information as possible including the name, location, and date of the event you attended, or any relevant links that provide context (e.g. Slack, GitHub). 

## Request an Accommodation 

To request an accommodation for a Carpentries event, please fill out the accommodation request form. 

If you have questions or need assistance with the accommodation form please [email us](mailto:team@carpetntries.org). 

## Resources 

[The Carpentries Toolkit of IDEAS | Zenodo](https://zenodo.org/record/7041935#.Y--_MWnMJD9)
The Toolkit of IDEAS (Inclusion, Diversity, Equity and Accessibility Strategies) is a practical resource for Carpentries’ Instructors, helpers, and workshop hosts. We know that many people care about inclusion, diversity, equity and accessibility but are not sure how it connects to teaching foundational coding and data science skills. This toolkit aims to bridge this gap. This is version 1, which means it is a starting point and not a fully comprehensive resource. The hope is that the Core Team and community members will continue to update and extend this resource over time.

**Comment by maneesha** [comment]
Hi @brynnelliott  Right now the "Equity, Inclusion, and Accessibility" menu option in the "About" section goes directly to the external Zenodo page.  Are you requesting a **_new_** page within The Carpentries site with the content above - and have that menu option go there instead of the external Zenodo page? 

It's not a problem to do that - just want to make sure. Thanks!

**Comment by brynnelliott** [comment]
@maneesha  Correct! I do not want the "Equity, Inclusion, and Accessibility" to go directly to the Zenodo page.

**Comment by maneesha** [comment]
Closing here as this is being addressed with #1588
