### ISSUE TITLE
Update CAC membership/leadership

### ISSUE THREAD

**Issue by ndporter** [carpentries/carpentries.org-archive#1602]
The [Curriculum advisors page](https://carpentries.org/curriculum-advisors/) page needs updates to leadership and possibly membership. For DC:SS, the list should be:
- Eirini Zormpa (Co-chair)
- Nathaniel Porter (Co-chair)
- Macarena Quiroga
- Daniel Woulfin
- Claudia Engel
- Edwin Bakiza

I'm not certain where the lists are being pulled from, so I can't submit a pull request for the changes myself.

It's probably worth double checking the other membership/leaderships as well.

**Comment by maneesha** [comment]
Hi @ndporter The data comes from [this yaml file](https://github.com/carpentries/carpentries.org/blob/main/_data/curriculum_advisors.yml). You are welcome to put in PR for review. 

Also tagging @tobyhodges to check on this and other Curriculum Advisors info.
