### ISSUE TITLE
replace jekyll-get-json with our own generator

### ISSUE THREAD

**Issue by zkamvar** [carpentries/carpentries.org-archive#1613]
@maneesha noticed problems with the jekyll-get-json gem that we use in our config to fetch our feeds, but not store them locally:

https://github.com/carpentries/carpentries.org/blob/8b668b173694899668e5ba0791df73239421e723/_config.yml#L136-L157

In essence, the gem fails to fetch the JSON on her machine, but it fails silently. We spent an hour trying to debug it, but to no avail. I asked for a solution on Mastodon and [Scott Chamberlain suggested to use a Generator](https://fosstodon.org/@sckottie/110192681364545913) to port the Gem into our website instead of relying on a third-party gem. 

Info on Generators: https://jekyllrb.com/docs/plugins/generators/
Link to original gem: https://github.com/brockfanning/jekyll-get-json/blob/master/lib/jekyll-get-json/converter.rb

**Comment by maneesha** [comment]
Closing this not relevant to the new website.
