### ISSUE TITLE
The instructor map shows people in the middle of the Atlantic

### ISSUE THREAD

**Issue by martinosorb** [carpentries/carpentries.org-archive#1619]
Hi all, there are 10 instructors listed on the instructors map as being in the middle of the ocean, east of Bermuda. Is there a reason for this?

(I love the map by the way.)

**Comment by maneesha** [comment]
Thanks for catching this @martinosorb.  This was due to a typo in our database records.  I've fixed the typo.  

I'm keeping this issue open to investigate more though, because this change is not making its way to our web servers and I need to figure out why.

**Comment by maneesha** [comment]
This has been resolved.

**Comment by martinosorb** [comment]
Thank you!
