### ISSUE TITLE
Investigate how to export google calendar links to ics

### ISSUE THREAD

**Issue by zkamvar** [carpentries/carpentries.org-archive#1623]
Someone from the maintainer onboarding would like to get the calendar invites via ICS, but our website only allows people to export via google. I'm not sure the solution right now, but I'm putting it here for posterity.

**Comment by maneesha** [comment]
You can access the calendar from your google calendar account by clicking on the "Google Calendar" icon on the bottom right of the [embedded calendar](https://carpentries.org/community/#community-events).
That gives you this [public ics link](https://calendar.google.com/calendar/ical/oseuuoht0tvjbokgg3noh8c47g%40group.calendar.google.com/public/basic.ics).

I am not familiar with how ICS works. When I tried using that link, it downloaded an ics file to my computer (with the entire history of Carpentries events - 2500+ events).  So it would stall while loading.  Also, as it is a downloaded file, I don't know if there are any settings that ensure this is a live feed.  

Keeping this issue open to discuss and explore more.

EDIT to add - @zkamvar if you want to share this with the maintainer in question and have them  try it out, that would be great.  If it works, we can add a link to the ics feed to our website to make it easy to access.

**Comment by zkamvar** [comment]
Thank you for checking this, @maneesha! IIRC, it was @bisaloo who made the request and he also mentioned that Maëlle Salmon (not tagging her because she's on vacation) has a method for adding ics links the ROpenSci page. 

Looking into this, it seems that they have a Hugo site that has [an ics template](https://github.com/ropensci/roweb3/blob/main/themes/ropensci/layouts/events/single.ics) with an events page, which maybe then seems like they are using their webpage to schedule events as opposed to a central calendar.

**Comment by Bisaloo** [comment]
Hi @maneesha & @zkamvar :wave: :wave:!

Thanks for sharing the ics link! I can confirm I managed to add it to my calendar. I believe my calendar software should be able to fetch updates automatically from this link but I'm available for a test if you want to modify or add a new event now that I've added it.

**Comment by maneesha** [comment]
Hi @Bisaloo ! 
I just created a test event on 1 December 2023.  Let me know if you can see that.

**Comment by Bisaloo** [comment]
I do!

As you mentioned before, it takes a little bit of time to sync because the calendar contains a large number of events but it seems to be working nonetheless.

**Comment by Bisaloo** [comment]
I'm now overwhelmed by the quantity of events so I probably won't keep it though :grimacing: :see_no_evil:

**Comment by zkamvar** [comment]
> I'm now overwhelmed by the quantity of events so I probably won't keep it though

My solution has been to copy the events I'm interested in over to my calendar (e.g. maintainer meetings) and set them to repeat at the same frequency, but yeah, it can be a bit intimidating

**Comment by maneesha** [comment]
Yeah, there are a lot of events - as noted above, my calendar kept freezing when I tried to load it.

Copying events is generally not recommended because you won't be aware of any changes made to the source calendar.

@Bisaloo Would you recommend that we offer this option as a link with the google calendar? I an put in a PR to do so.  Otherwise I'll close this issue.

**Comment by zkamvar** [comment]
FWIW, the ROpenSci calendar link a single event, but they somehow are able to get it to synchronise (see https://ropensci.org/events/). I can follow up with Maëlle Salmon after the Workbench transition to see how they did it.

**Comment by Bisaloo** [comment]
> @Bisaloo Would you recommend that we offer this option as a link with the google calendar? I an put in a PR to do so. Otherwise I'll close this issue.

Yes, I would probably still recommend it. The "too many events" issue is somewhat a different one. People who uses the google calendar option will be exactly in the same situation.
In other words, I see adding the ics link as a net improvement compared to the current situation. With this change, users without a google account will now be able to do the same thing as users with a google account.

> FWIW, the ROpenSci calendar link a single event, but they somehow are able to get it to synchronise (see [ropensci.org/events](https://ropensci.org/events/)). I can follow up with Maëlle Salmon after the Workbench transition to see how they did it.

My understanding is that your calendar software will `GET` the link on a regular basis (every 30min by default in my case). If the contents of the ics file change, it should be able to pick it up seamlessly.
(Now that I think about it, this probably means that it's not even trying to optimize transfer size by doing things like delta updates :thinking:.)
