### ISSUE TITLE
Objectives missing online.

### ISSUE THREAD

**Issue by jnagan** [carpentries/carpentries.org-archive#1639]
I found the learning objectives for the Data Analysis and Visualization in R for Ecology was missing on the learner's lesson [webpage](https://datacarpentry.org/R-ecology-lesson/index.html). The learning objectives are available to the instructor through the R [markdown](https://github.com/datacarpentry/R-ecology-lesson/blob/main/episodes/01-intro-to-r.Rmd) file, but it would be beneficial for the objectives to be available to the learners as well.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

**Comment by maneesha** [comment]
Thanks for raising this @jwagan 

@carpentries/core-team-curriculum Would you like to see this issue moved to https://github.com/datacarpentry/R-ecology-lesson ?

**Comment by zkamvar** [comment]
Yes, it should be moved there, but unfortunately, we cannot transfer issues between GitHub organizations.

**Comment by tobyhodges** [comment]
This is a result of the transition to the new lesson infrastructure, which [requires a `questions` block](https://carpentries.github.io/sandpaper-docs/episodes.html#questions-objectives-keypoints) in addition to the `objectives` block present in the source .Rmd files. Most lessons had questions for each episode already, but this one did not. To fix it, these questions blocks need to be added to each episode.

Thank you for raising this, @jwagan

**Comment by tobyhodges** [comment]
Closing here in favour of https://github.com/datacarpentry/R-ecology-lesson/issues/850
