### ISSUE TITLE
add list of workshops

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#164]
We have the Data Carpentry, Software Carpentry and Library Carpentry workshops on the different websites. It would be good to also have a 'master' list of the workshops on the main site.

**Comment by weaverbel** [comment]
I agree but am not sure how to build this as it would require feeds from AMY. @jduckles @fmichonneau @maneesha do any of you know how to achieve this?

**Comment by maneesha** [comment]
I don't know how to do this.  I imagine the method would be similar to how it's done on the SWC and DC websites, just without filtering for workshop type.

I don't know how much this matters but I believe that on the SWC website is automatically updates.  I believe @tracykteal  is working on making that happen with DC as well (DC website sometimes requires manual updates)

**Comment by jduckles** [comment]
I've laid the ground work for this over at https://github.com/carpentries/amy-feeds
