### ISSUE TITLE
Incorrect spelling of name on Carpentries timeline image

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#1685]
On this post on the blog, Jonah Du**c**kles is wrongly listed as Jonah Du**n**kles.

https://carpentries.org/blog/2023/07/carpentries25-campaign-announcement/

Can you please amend the image to reflect the correct spelling which is DUCKLES?

**Comment by maneesha** [comment]
Thanks for catching this @weaverbel 
Tagging @acrall as I don't know the source of this image.

**Comment by acrall** [comment]
Thanks for noticing this @weaverbel! We had corrected in other locations but forgot to do so here. It is now fixed
