### ISSUE TITLE
Members map not displaying due to extra comma in json

### ISSUE THREAD

**Issue by davidwyld** [carpentries/carpentries.org-archive#1745]
I noticed that the members map is not displaying on the site. JS console shows

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1185 column 3 of the JSON data
```

I served the site locally and downloaded the `all_members_by_location.geojson` file (from https://feeds.carpentries.org/all_members_by_location.geojson), which is slightly malformed.

The last record (below) has a comma.

lines 1172-1182
```json=1
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates":[-112.0645841529991,33.523942893234064]
      },
      "properties": {
        "marker-color": "#2b3990",
        "details": ["Arizona State University"]
      }
    },    
```

Locally, removing the comma eliminates the error.

**Comment by maneesha** [comment]
This was due to an error in our feeds and has now been fixed.
