### ISSUE TITLE
Updating EC/Governance reports 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1769]
On the [reports page](https://carpentries.org/reports/) we have EC reports for 2018 and 2019.  @kariljordan  what should we link to for years 2020-2023? 
(Note I have a separate PR to update the title of this section to "Governance")

**Comment by kariljordan** [comment]
Thank you for noticing/remembering that - I totally forgot. Yes please, let's link to those reports.

**Comment by maneesha** [comment]
@kariljordan The links on the reports page go to blog posts.  I skimmed the blog posts for the past few years but did not see similar blog posts after 2019. What would you recommend linking to?

**Comment by kariljordan** [comment]
2020 - [Amending the Carpentries Bylaws in 2020](https://carpentries.org/blog/2020/12/carpentries-executive-council-bylaws-revision-2020/)
2021 - [Executive Council Key Activities Report](https://carpentries.org/blog/2021/12/executive-council-key-activities/)
2022 - [Executive Council Key Activities Report](https://carpentries.org/blog/2022/04/executive-council-key-activities/)
2023 - [Highlights from the 2023 Executive Council Retreat](https://carpentries.org/blog/2023/05/EC-retreat/)
