### ISSUE TITLE
add info about workshop coordinators?

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#179]
A couple of people at CarpentryConnect Davis asked me about how to get in touch with their regional workshop coordinator (in this case for the UK). I realized that we don't have this information on the website and I also don't know in what cases it would be useful for people to contact their regional coordinators rather than central staff. I'm putting this issue in just to start a conversation about whether we should add that info and if so how/where.

@maneesha @sheraaron

**Comment by sheraaron** [comment]
@ErinBecker this is great! It would be good to have this on the website. If they are looking to organize workshops they would go to their regional workshop coordinator. I must say, if they reach out to staff, @maneesha  and I will send the request to the Regional coordinator and ask them to respond so that they can build rapport.

**Comment by maneesha** [comment]
Thanks @ErinBecker 
You are definitely right, that a lot of people don't know the workshop admins.
This month I am having individual meetings with all the workshop admins and one major point of discussion will be managing contacts and communication systems.  We'll look into how to update the website based on how things go with these conversations.

**Comment by jduckles** [comment]
I like the idea of this being a data-driven page. Could we "award" in AMY a "workshop coordinator" badge? Then their profile data can be accessible on a workshop admins page with the coordinators arranged by the country of their airport record in AMY. Look for a new issue with a proposal on how to do this for [Instructors, Trainers, Maintainers, Mentors, Mentees, Workshop Coordinators, Workshop Organizers, Executive Council Members, Executive Council Alumni, Staff] all driven by AMY records.

**Comment by jduckles** [comment]
FYI: The automated segments I mentioned above are being tracked, worked on over at #182.

**Comment by weaverbel** [comment]
Now this is being worked on in issue #182 I am closing this one.
