### ISSUE TITLE
Adding Committe Chairs to Governance Page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#1795]
The following are the names of the Chairs of the Standing Committees of the Board of Directors and I'd like help with a PR to update the [Governance Page](https://carpentries.org/governance/) with that information.

Finance Committee - Michael Smith
Audit Committee - Mark Crowe
Program Committee - Nisha Ghatak
Governance and Personnel Committee - Tara Robertson

Thank you! I tried submitting the PR but the code looks like nothing I've worked with before.

**Comment by maneesha** [comment]
Fixed with #1799
