### ISSUE TITLE
weird line spacing 

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#18]
On the [join us page](https://carpentries.github.io/new-website/community/) there is an empty line between a bullet item and the next line (in the TOC at the top of the page). Would like to get rid of that blank link (and ideally add space between bullet items), but I'm sure this is buried in the CSS somewhere.

**Comment by jduckles** [comment]
Fixed by 77144524d0b023e4993589792cb36b4454f6fa1e
