### ISSUE TITLE
Generating information pages for community directory

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#182]
# Overview
We want to be able to generate from AMY data, periodically (daily/hourly) updated HTML for pages listing each of:

**Immediate priorities:**
* Instructors (by badge: SWC, DC, LC etc)
* Trainers
* Maintainers 
* Mentors 
* Mentees 
* Workshop Coordinators (arranged by country)
* Workshop Organizers (maybe not)

**potential future contact data views:**
* Executive Council Members
* Executive Council Alumni
* Committee membership/leadership
* Staff ?

**Others**
* Member Organizations
* Voting Members (based on teaching record)

# Background

Most of these categories of community participants have an "awarded" badge in AMY. There is an AMY api which will allow us to dump these records (`/api/v1/person/`). 

The base information to draw from will be:

1. Profiles where consent has been given to share profile information `publish_profie` in AMY
1. Profile records [ name, github, twitter, orcid, url, md5(email)†  ] 

† Note: md5(email) will allow us to use [gravatar images](https://en.gravatar.com/site/implement/hash/) of members in a privacy preserving manner.

There will views generated for each of the members of the above sets of categories. 

# Action required

- [x] query AMY to provide the information needed (will do this manually from sqlite db initially, from API eventually)
- [x] mockups of list views and personal views with
- [x] data + mockups -> templates
- [x] automate updates probably in [amy-feeds](https://github.com/carpentries/amy-feeds/)

**Comment by weaverbel** [comment]
I would question why we would want to list mentees @jduckles - do you think that is desirable? I think that information should be private but maybe I am wrong. What do you think @kariljordan ?

I would like to see Curriculum Advisory Committee members listed though.

**Comment by kariljordan** [comment]
I do not see a reason to list mentees for several reasons. Right now we don't have a way to track whether or not mentees are active. I also think we should highlight more of the leadership positions on this page. Eventually we hope mentees will become mentors or serve in another capacity, so those who are active will probably be listed on this page at some point.

**Comment by jduckles** [comment]
This is now complete and implemented for all the badged segments of the Carpentries. When bylaws come out and go into effect we can also think about adorning profiles with "Voting Member" bling of some kind. Closing as this is all in place and working now.
