### ISSUE TITLE
Updating governance page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#1841]
Tara Robertson is no longer a member of the Board of Directors. I was about to submit a PR to update the [governance page](https://carpentries.org/governance/), but removing the photo, etc. is outside of my skillset. May I please have some assistance?

**Comment by maneesha** [comment]
@kariljordan  PR #1842 is ready for your review.

**Comment by kariljordan** [comment]
Thanks so much, @maneesha. I approved the PR.

**Comment by maneesha** [comment]
Fixed with #1842
