### ISSUE TITLE
Software Carpentry's Reading material

### ISSUE THREAD

**Issue by dpshelio** [carpentries/carpentries.org-archive#1848]
In the old software-carpentry's site, there was a section under Get Involved/Reading material ([archive](https://web.archive.org/web/20231010045010/https://software-carpentry.org/reading/), [removal commit](https://github.com/swcarpentry/website/pull/1272/commits/79eed1f5c9633e4f5fcb153cf3f53e8d9f6b760d#diff-f1ccc9b7b2a33f7bde266dd8f668bad42fc205fac0fd361d607dc803fa48a0b2)) that I have shared with many people over the years (last one being this last Friday!) and used as a good set of resources. However, that's not there any more and neither in the Carpentries site.

**Comment by maneesha** [comment]
Hi @dpshelio Thanks for bringing this up.  It is good to know that you found those resources useful. However, the list of resources is many years old. We have chosen to take this down for now and will consider replacing it with a curated and current list of resources.
