### ISSUE TITLE
Fix bug in "authors" metadata property in YAML frontmatter.

### ISSUE THREAD

**Issue by NPDebs** [carpentries/carpentries.org-archive#1857]
Hi folks. 👋 

In the [`post-by-authors` page](https://carpentries.org/blog/posts-by-authors/#blog-author-toby-hodges), there are two instances of Toby Hodges as an author. This resulted from a bug in the [`dc-r-ecology-adoption`](https://carpentries.org/blog/2024/03/dc-r-ecology-adoption/) post, specifically in [this line](https://github.com/carpentries/carpentries.org/blob/c363154840c70b19586fcaecb48e266b29355fe8/_posts/2024/03/2024-03-27-dc-r-ecology-adoption.md?plain=1#L3).

<img width="1465" alt="Screenshot 2024-09-15 at 13 01 38" src="https://github.com/user-attachments/assets/104f59fd-b02e-473e-88f9-e01e658ed978">

<img width="828" alt="Screenshot 2024-09-15 at 13 02 55" src="https://github.com/user-attachments/assets/5a852dcc-ef10-4050-acac-5ee2d2c6803c">

It is a relatively easy fix (since it's missing just a double quote) and I'll be creating a PR for that in a sec. Thanks!

**Comment by maneesha** [comment]
Closed with #1858
