### ISSUE TITLE
FAQ on what is a SWC/DC workshop

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#197]
https://info.carpentries.org/article/67-can-i-call-my-workshop-a-swc-dc-workshop seems tailored toward new instructors, but I suspect many established or non-instructors will also reach out to it. I did because I wanted to find the current rules for what a branded SWC workshop should be teaching.

Suggestions:

* rewrite the start
* include rules for link to them
* include rules for DC workshop

**Comment by weaverbel** [comment]
The whole FAQ needs revisiting post-merger - I will try to take a look at that one tomorrow - it is end of day here. Have you got anything to suggest that should be listed?

**Comment by lexnederbragt** [comment]
I was going to suggest some language, but I'd prefer to point to places on carpentries.org and/or https://software-carpentry.org & http://www.datacarpentry.org where the rules are laid out. All I could find was "In order to use the {Software,Data} Carpentry name and logo at your event, we only require that you follow our curriculum, have at least one badged instructor teaching and co-organizing your event, and let us know that you’re organizing a workshop." 

I found this for SWC: https://info.carpentries.org/article/12-what-is-the-core-of-software-carpentrys-curriculum but.

The best I can come up with for DC is this https://datacarpentry.org/lessons

Would that suffice?

(carpentries.org has a little bit here: https://carpentries.org/about/)

**Comment by weaverbel** [comment]
Thanks @lexnederbragt 

I have created a sheet to list all the FAQs and where I think they should live: https://docs.google.com/spreadsheets/d/1ByElpgFJx9DreFXH2sFD2mzbhHN_vOHJc9LCzmnb1Wo/edit#gid=0

We will gradually start to move stuff over and remove links until we can shut down the FAQ altogether. We really only want stuff on the website or the handbook.

**Comment by ErinBecker** [comment]
Great list @weaverbel, thanks for putting this together! Let me know if you'd like me to look over the list in more detail and offer any suggestions (as part of the Comm's team). Also pinging @libcce in case he has any feedback. I'm really looking forward to seeing all of this information come together.

**Comment by lexnederbragt** [comment]
Thanks, @weaverbel. I had a look at the list and I feel this will work fine as suggested. Shall I close this issue, then?

**Comment by weaverbel** [comment]
Sure. We are actively working on sorting this now. Thanks.

**Comment by maneesha** [comment]
Much of this has been migrated to the handbook so I'm closing this.  Anyone can feel free to re-open if things are not working.
