### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#198]
Where does the FAQ live on GitHub? Or I guess, https://info.carpentries.org? Could a button 'improve this page' be added so it become much easier for the community to help improve the text?

**Comment by rgaiacs** [comment]
<del>I think it is https://github.com/carpentries/handbook.</del>

> Where does the FAQ live on GitHub?

It is not GitHub. It is https://www.helpscout.net/.

> Could a button 'improve this page' be added so it become much easier for the community to help improve the text?

@weaverbel ?

**Comment by weaverbel** [comment]
Hi @lexnederbragt and @rgaiacs 
I have a current task of migrating all the FAQ material from HelpScout into either the handbook or the website. We will then retire the HelpScout info altogether, as we don't want to manage so many platforms and as Lex has said, there is no easy path to correct or update older or inaccurate info. For now, please send any updates to me and I will fix them.

I realise this is not ideal and getting the FAQ sorted is not my highest priority at the moment - there are others things that are more pressing - but I will certainly fix any that are obviously wrong or where it would really help to add more info.

**Comment by lexnederbragt** [comment]
Thanks, closing as "on someone's todo list waiting for priority"
