### ISSUE TITLE
docs.carpentries.org vs info.carpentries.org

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/carpentries.org-archive#199]
I think that the content of info.carpentries.org should live inside docs.carpentries.org. Have two places is confusing and increase the maintenance burn.

@lexnederbragt What do you think?

**Comment by weaverbel** [comment]
This info is going to be migrated into either carpentries.org or the handbook. We will no longer use info.carpentries.org. I will close this issue now as we have dealth with this in the other issue #198 .
