### ISSUE TITLE
Add summary stats to main page

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#208]
The Community Development team is going to work to add some call-out numbers to the website that help website visitors see our impact.

Example:

![image](https://user-images.githubusercontent.com/119403/44687065-4859c000-aaa4-11e8-9e7d-ae3cd82f727a.png)

![image](https://user-images.githubusercontent.com/119403/44687087-590a3600-aaa4-11e8-9d90-a92fb7d1e354.png)

* [ ] -  Add layout elements to page (Jonah)
* [ ] - identify what queries/data from AMY will feed these numbers (Kari and Sher)
* [ ] - Wire up queries to feed yaml files. (Jonah)

**Comment by kariljordan** [comment]
@maneesha here is a little background. The community development team has been looking at websites from other community organizations that we like and pulling out "low hanging fruit" that we can apply to our website to make it more welcoming. We'd like to add some call out numbers/metrics, but we want to make sure that: 

1.  We can pull them directly from AMY or another data source
2.  The metrics are compelling, i.e. if there are "0 workshops this month" we may not want to show that metric.

I would like to get your perspective as you are very familiar with our programmatic assessment. What kind of metrics would pique the interest of someone browsing our website?

**Comment by maneesha** [comment]
I'm really glad to see this conversation happening.  I'm excited to look at ways we can share data about our impact.

I have a few questions looking at your examples so I can better understand your vision and motivation for doing this.

Would you want the metrics to be the same each month?  (For example, every month we show the number of workshops)  OR something different each month (like September shows number of workshops, October shows number of instructor trainings, December shows number of members, etc.)

Would you want the metrics to be lifetime or month specific? Either way the numbers will have to be updated each month.

Do you want metrics that are just about *our* numbers? (like the example "2133 students employed on campus") OR external metrics that demonstrate our need for existing (like the example "7000 students drop out of high school each day")?

What is the purpose of showing something like this?  Is it to provide "soundbytes" of data?  Is it to motivate people to learn more? Is it to motivate people to do something?  Understanding this would help determine what kind of data we should share.

@jduckles  Can you share the actual websites the screen shot snippets you included above came from? I'm curious to see the context that these data points appear in.

**Comment by jduckles** [comment]
One is from http://mtu.edu the other from https://www.unitedway.org these were provided by @kariljordan  as an example to the Community Dev team. I think we want to have these numbers fed to some kind of query that is changing weekly/monthly. 

So maybe things like:

- Number of workshops in the trailing year
- Number of countries hosting workshops in trailing year
- Number of organizations running workshops in some trailing time-period
- Total number of badged instructors
- Number of countries with badged instructors

We can always hotlink these numbers to data feeds and deeper analysis in the future. The idea in the short-term is to help us as a community talk about these kinds of metrics and numbers as measures of our reach and impact and how we're all working to grow them together.

**Comment by maneesha** [comment]
Thanks @jduckles 
All of those are fairly easy to gather.
By "trailing year" I assume you mean last 12 calendar months?   (so it changes every month, rather than calendar year, meaning we'd show data for 2017 all year in 2018)

We should be consistent with what time period each metric reflects - trailing year or some other trailing time period.  

I also like the idea  of having external metrics that demonstrate our need for existing (like the example "7000 students drop out of high school each day") -- although I really don't know what those metrics would be.  Maybe something from the pre-workshop survey that @kariljordan  analyzes, where we see things like what percentage of people state they've never had computational programming training.

I'm also looking to understand *why* we are doing this. We may all have implicit reasons why we should do this, but having those reasons open and explicit is useful. 

> What is the purpose of showing something like this? Is it to provide "soundbytes" of data? Is it to motivate people to learn more? Is it to motivate people to do something? Understanding this would help determine what kind of data we should share.

**Comment by kariljordan** [comment]
The way it's currently set up, I would have to manually change the "data soundbites" using the learner data from SurveyMonkey. I have no problem doing this, but we talked about using data from AMY as it would be automatically fed to the website.

The purpose of providing these figures on the website is to **highlight The Carpentries major outputs**. In our Community Development Team [meeting notes](https://docs.google.com/document/d/1ImQzc3fAXq4_nri5WfsQ5vRCnPm6E_jlZIZXWrBMWPY/edit) we've outlined several community websites that we felt were welcoming and why we thought they were welcoming. Highlighting our "output"/assessment results will draw people into our website, and hopefully make them ask questions like "how can/should I get involved?"

**Comment by kariljordan** [comment]
Checking in on this issue. I'd like for us to set a deadline for having this issue closed. @maneesha, did you have more thoughts on what numbers/figures to use? Can we have something up in 2 weeks? If that's reasonable, I'll add a few tasks in Asana to map this out (similar to Jonah's checklist).

**Comment by weaverbel** [comment]
Can this be closed now we have the volunteer page with numbers on it? I know those figures are not  updated in real time.

**Comment by jduckles** [comment]
Yes.
