### ISSUE TITLE
Donate text to red

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#210]
Many websites we were looking at on community dev have callouts for Donations in Red text. We're going to try it.

**Comment by weaverbel** [comment]
Where does it need to be changed?

**Comment by jduckles** [comment]
I've looked into this and the way the menus are driven by a yaml document is going to complicate this.

**Comment by maneesha** [comment]
@jduckles  do you want to pursue this?

**Comment by maneesha** [comment]
@elizabethwilliams8  This may be in your realm now... do you think we should pursue this?

**Comment by elizabethwilliams8** [comment]
I think @tracykteal is planning to look into a re-design of the website anyway, and this should be considered in that context. And I don't think it is a priority. I agree with making the donate button eye-catching, but red would be a bit jarring on our website, I think.

**Comment by tracykteal** [comment]
Yes, I think this goes into a general idea about a donation campaign. So, we can plan to do an update as a part of that project. I'll make a note to keep track. But I think we can close this issue.
