### ISSUE TITLE
Anelda van der Walt's keynote video recording is missing in the report blog post

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/carpentries.org-archive#223]
https://carpentries.org/blog/2018/09/carpentrycon-call/ has links to all the other keynote video recording except for Anelda's one. The video is available on the YouTube playlist, https://www.youtube.com/playlist?list=PLXLapl_LKb4csrVg1nxBEG5H6B7PmN-rx. @weaverbel or @ErinBecker, could you fix it as authors of the blog post. Thanks very much.

**Comment by weaverbel** [comment]
Yes, this was a very late addition - I will add it @rgaiacs

**Comment by weaverbel** [comment]
Added
