### ISSUE TITLE
Simplistic carpentries website for local teaching organizations

### ISSUE THREAD

**Issue by darencard** [carpentries/carpentries.org-archive#229]
This is less of an issue and more of a request for some feedback and guidance. I'm involved with a group of instructors at University of Texas, Arlington, where we've run half a dozen workshops on campus over the last several years. Our university recently signed on as a member organization and as a group we're interested in putting together a website for our local organization. In looking at ways to do this, I like the idea of using a somewhat stripped down version of the Carpentries website so that design is consistent with the national organization, etc.

First, I want to make sure such a thing is permissible. I'm assuming it is given we're a member organization and that all materials are open source. Second, I was just hoping to get some feedback on this as a plan and on any considerations or potential difficulties we may encounter if we were to do this. We have some server space and a Carpentries URL from our university, so it appears we could clone appropriate repositories to that server, cut out pages we don't need, perform some other customizations, and then serve accordingly. Any feedback or other information would be greatly appreciated. Moreover, if there is a way to seek help as we do this that doesn't clog up Github issues or other places, then please let me know about that as well.

Thank you,
Daren Card

**Comment by jduckles** [comment]
@darencard This is a great case for using GitHub Pages, just like we do in The Carpentries, you won't even need server space on your university servers. You can host directly at a GitHub Pages url `https://<yourorganizationname>.github.io/`, you can also point the university domain to GitHub pages if that is allowed by your university policies.  

Some examples of other community members doing this are:
1. [University of Florida Carpentry Club](http://www.uf-carpentry.org/) - ([GitHub repo](https://github.com/UF-Carpentry/website))
2. [North East Software Carpentry Library Consoritum](https://nesclic.github.io/home/) - ([GitHub repo](https://github.com/NESCLiC/home))

These two initiatives came about on their own (with little staff involvement), however, these approaches closely mirror our approach to how we manage our website as well. We're happy to support you as you work to get this going for your team. 

All of our work is CC-BY and you're free to take it and run with it with attribution. That being said, our websites themselves are built upon an underlying template called ["Feeling Responsive"](https://github.com/Phlow/feeling-responsive). I would not actually recommend you use Feeling Responsive as it is a sledgehammer for what you're looking to accomplish. Picking a GitHub pages default template and adapting it to your needs is what I would recommend.

If you do go through this process, I'd love to work with you to help build out the steps for our [community cookbook section on the topic](https://cookbook.carpentries.org/communities-need-useful-tools-to-help-them-organise-and-connect-we-list-a-few-here-that-might-be-of-use-.html#gitgithub)([source markdown](https://github.com/carpentries/community-cookbook/blob/master/04-tools.Rmd#gitgithub)).

**Comment by darencard** [comment]
Thanks @jduckles!
