### ISSUE TITLE
newsletter page not looking so good

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#238]
I think there's a bug in the newsletter page somewhere. the footer is not the right size. Also, the privacy policy link is displayed as text rather than a hyperlink. And there is no link to previous issues of the newsletter. I remember it looking really snazzy before, so something must have gotten off somewhere: 

![screen shot 2018-09-28 at 8 20 10 pm](https://user-images.githubusercontent.com/19176319/46240412-ea96ed00-c35b-11e8-8025-efc75c15c34e.png)

**Comment by weaverbel** [comment]
The page has not been changed at all - it was last updated months ago when Francois changed it. Not sure what is going on but the list of newsletters has disappeared from the page too.

**Comment by weaverbel** [comment]
I don't think the problem can be in the newsletter page (which has not changed) but in one of the forms that populates the page: probably this one: `mailchimp_signup_form.html` which was changed within the last 2 days by @jduckles . Jonah, can you please have a look and see if there is something in this form that might have broken the page? The other bit of the page is not loading - the list of older newsletters.

**Comment by weaverbel** [comment]
The newsletter page is still broken, so I am reopening this issue.

**Comment by weaverbel** [comment]
In addition to the wonky display, the past issues of newsletters part of the page is not loading.

**Comment by jduckles** [comment]
When testing locally it looks fine:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/119403/46322424-49eb4a80-c645-11e8-8e11-726bea64d5f1.png">

I'll revert to last known working state and we can leave this issue open until someone has time to figure out what is going wrong.

**Comment by fmichonneau** [comment]
looks OK now? https://static.carpentries.org/newsletter/
