### ISSUE TITLE
Make community calendar adjust for timezones

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#243]
Right now the community calendar on our website always shows events in US Eastern time.  There is a way to have a calendar detect the user timezone and adjust accordingly.  See the script at the top of this page:  https://github.com/carpentries/handbook/blob/master/topic_folders/communications/zoom_rooms.md

I'm not sure with the way carpentries.org website is built, if we can insert this script at the top of the page or if it needs to go somewhere else.

**Comment by fmichonneau** [comment]
if we don't use the feature anywhere else on the website, I think it's reasonable to include the script in the md file for this page, just like you did for the handbook. From what I understand, it's better to put it at the end of the file rather than at the top.

**Comment by maneesha** [comment]
Fix attempted with https://github.com/carpentries/carpentries.org/pull/266
