### ISSUE TITLE
One column format for main page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#247]
One of my favorite web services is **[Splash That](https://splashthat.com)**. I like the way their homepages are built in single column format and they look really clean. Is there a way for our homepage (the first page you see when you go to [carpentries.org](carpentries.org) to look like this?

[Here](https://splashthat.com/event-management) is another example page that looks very clean.

**Comment by weaverbel** [comment]
I think those pages do look nice @kariljordan but I think the comms team might feel a little busy for a while so this may be a low priority.

**Comment by kariljordan** [comment]
That is fine. I added this in response to your request for staff to look at the carpentries.org website and add issues to the repo.

**Comment by weaverbel** [comment]
Definitely worth adding as an issue but I think it would take quite a bit of work as there are a lot of fiddly bits that make up the hone page. Thanks for taking the time to look things over though.

**Comment by maneesha** [comment]
@kariljordan  Checking to see what you think since you opened this issue.  Do you still want to revisit this to consider what we can do?

**Comment by kariljordan** [comment]
I think we can close this for now. One of these days we can put focused attention on website improvements as a whole.
