### ISSUE TITLE
Members page lists U. Oklahoma twice

### ISSUE THREAD

**Issue by drammock** [carpentries/carpentries.org-archive#261]
...once under "Platinum" and once under "Gold".  Happy to submit a PR if someone tells me which one is correct.

https://carpentries.org/members/

**Comment by maneesha** [comment]
@elizabethwilliams8   Could you let us know how they should be listed so we can make the change?

**Comment by elizabethwilliams8** [comment]
thank you for catching this! They have moved up to Platinum this year. I will fix this ASAP.
