### ISSUE TITLE
Consistency in how workshops are listed across 4 Carpentries sites

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#334]
This affects all our websites:  carpentries.org and the LC, DC, and SWC sites.  Just putting issue here for now.

- Workshop list on DC site builds from AMY, is on [front page](https://datacarpentry.org/) and lists upcoming workshops only.  Clicking through the top menu takes you to [past workshops page](https://datacarpentry.org/workshops-past/)  which is [currently empty](https://github.com/datacarpentry/datacarpentry.github.io/issues/475)
- Workshop list on SWC site builds from AMY, is on [front page](https://software-carpentry.org/).  Front page list includes a link to [past workshops with a map](https://software-carpentry.org/workshops/).  
- Workshop list on LC site is on [a different page](https://librarycarpentry.org/upcoming_workshops/), is a manually curated, and lists all workshops in the same place.

Would like to see workshops listed on all four sites in the same way.

**Comment by libcce** [comment]
I'd like to see LC's workshop page in alignment w/ The Carpentries. Only reason why it is manually curated is that we list LC-based/inspired workshops as well. If there is a way to log these workshops separately in AMY and list them w/ the standard workshops, that would be great!

**Comment by maneesha** [comment]
I've [just updated](https://github.com/carpentries/carpentries.org/pull/492) The Carpentries website to have dedicated pages for past and upcoming workshops.  
Data Carpentry and Software Carpentry have dedicated pages for past and upcoming workshops.  

Library Carpentry has them all on one page - and until we decide to automate the listing, I don't think it's realistic to have accurate future/upcoming pages.

Ideally all these sites should also have a similar look and feel and navigation experience, but that's for a different issue.

I'm closing this here and opening an issue to revisit this for the LC website.
