### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#344]
When I run `bundle install` on Ubuntu 18.04 I get this message.  I don't know what this means.  Since it's being deprecated soon I wanted to see if this is something we need to be concerned about.
Tagging people who may know more than me:
@fmichonneau @jduckles @charlesreid1 

```
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

```

**Comment by fmichonneau** [comment]
My understanding is that it will sort itself out. Future releases of jekyll on GitHub will  remove this dependency and switch to the Ruby gem mentioned in the message.
