### ISSUE TITLE
Instructor map lists instructors by initials only

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#359]
On this page:
https://carpentries.org/instructors-map/

Is this intentional? Do we want to list names of people who have opted in?

**Comment by fmichonneau** [comment]
yes, it's intentional as a way to protect our instructors' privacy. Making opt-in to have the full name displayed seems reasonable. That would however require changing the form in AMY to make sure people expressly agree to have their full names displayed on the map.

**Comment by maneesha** [comment]
OK, that's fine -closing this.
