### ISSUE TITLE
Include list of past workshops?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#368]
It looks like we don't have a list of past workshops on the main carpentries.org website. Is it something we should add? Personally, I think it'd be a good idea.

**Comment by libcce** [comment]
Agree! People use the Library Carpentry upcoming workshops list to see what has been taught, if something has been taught near them, etc. https://librarycarpentry.org/upcoming_workshops/.

**Comment by sheraaron** [comment]
Yes, I would like for the main carpentries.org website to be the central place to find anything related to The Carpentries.

**Comment by sheraaron** [comment]
as it relates to the workshops 😄

**Comment by tracykteal** [comment]
Yes, this is a good idea! I like how SWC and DC do it with a dedicated page of past workshops 

https://software-carpentry.org/workshops/past/
https://datacarpentry.org/workshops-past/

SWC has the map too. If we wanted to we could include a map.

**Comment by maneesha** [comment]
Fixed with #492
