### ISSUE TITLE
Mentoring groups - link to blog post or handbook?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#37]
On the Join page there is a bullet item:

> Join  a Carpentries mentoring group as a mentee.

This links to a blog post.  Should it link to the blog post or the handbook?

**Comment by maneesha** [comment]
Same thing for Curriculum Advisory Commitee linked to on the same site

**Comment by weaverbel** [comment]
@ErinBecker is working on a new Join page. This is a placeholder. Since all the info for mentees and CACs is in those blog posts, it seemed safest to link to them until the new page which will include that info in a static form is available. @maneesha

**Comment by weaverbel** [comment]
Since the other page is live now, I am closing this.
