### ISSUE TITLE
Include DOI to "The Carpentries 2018 Annual Report" blog post

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/carpentries.org-archive#370]
https://carpentries.org/blog/2018/10/annual-report/ should have a link to https://zenodo.org/record/1465064#.XFq8Gbrng7M for people that want to cite us.

@serahrono Can you do the change?

**Comment by ErinBecker** [comment]
Thanks @rgaiacs for the suggestion. @maneesha manages the websites, so I'll assign this to her.
