### ISSUE TITLE
Error in retrieving instructor orcid

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#374]
On the [instructors page](https://github.com/carpentries/carpentries.org/blob/gh-pages/pages/instructors.html) this line:

```      
{% if person.orcid_ %}<li> <a href="https://orcid.org/{{ person.orcid_ }}"> <i class="far fa-file-alt"></i> </a> </li> {% endif %}
```

seems to evaluate to  `True` for `NaN` meaning all instructors who don't have an orcid on file end up with a link to `https://orcid.org/nan`. 

Not sure how to fix this.  @fmichonneau ?

**Comment by maneesha** [comment]
This is still returning `https://orcid.org/nan`

**Comment by fmichonneau** [comment]
is this in your branch by chance?

**Comment by maneesha** [comment]
Yes... I hadn't refreshed my view on the live site :-(

**Comment by fmichonneau** [comment]
no problem!
