### ISSUE TITLE
Instructors should be on Carpentries site

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#38]
Right now when you click on Our Team --> Our Instructors it takes you to the SCF member page.
The SCF members represent a smaller group than the whole instructor pool which represents instructors who have not taught in the last two years.

**Comment by weaverbel** [comment]
Yes, but we would need to build a new list of instructors - I have created the maintainers and trainers from AMY lists but did not have time to create a new page of all instructors as that was a massive job. Lots of this stuff is 'placeholder' until we can create a new pull out of AMY. I don't know how to do that.

**Comment by maneesha** [comment]
We have this instructors page on the Software Carpentry website that includes all members who choose to be listed, regardless of the membership status.

The map is built from AMY.
The bios are *not* built from AMY but rather from the bios that instructors provided themselves.

https://software-carpentry.org/team/

**Comment by weaverbel** [comment]
Ok, will change my link over - thanks

**Comment by weaverbel** [comment]
Ok, link changed - nav building now.
