### ISSUE TITLE
Update reading material pages

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#384]
We have these two pages on the SWC and DC websites:
* https://software-carpentry.org/reading/
* https://datacarpentry.org/media/

In [another issue](https://github.com/carpentries/carpentries.org/issues/129) it is suggested that we redirect those to a page on The Carpentries website and have content organized there.  These two pages don't seem to be maintained though - content seems old and incomplete.  

How can we create a new page with content that is actively curated and maintained?  Feedback from @ErinBecker  and @tracykteal  is welcome.

**Comment by tracykteal** [comment]
Definitely should redirect these pages to something we're going to keep current. These two pages serve different purposes though. On the Carpentries site, we could have a 'News' page that we keep up to date. Reference type reading would be different, so we'd have to think if we'd want to do that and where it might go. Right now that sort of thing is more incorporated into lesson notes.

**Comment by maneesha** [comment]
@serahrono  is this something you'd like to keep open? Are we reconsidering how we share reading material?

**Comment by maneesha** [comment]
@acrall  and @kmomar  Let me know if this is some thing we should keep open.  Our reading material pages are quite outdated so we may want to consider revamping this completely.

**Comment by kmomar** [comment]
@maneesha @acrall we are planning to wait for the new website to see the best way to transition this info to our main website. In terms of keeping this info updated, perhaps there is a way to get the community involved.

**Comment by maneesha** [comment]
I am closing this, to be revisited in developing our new website.
