### ISSUE TITLE
orcid icon is out of alignment and just a dot

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#385]
See for example 
![image](https://user-images.githubusercontent.com/829690/53203081-2a55be00-35f6-11e9-8eee-47e494674646.png)

Looks like this happened when the style was changed here:  https://github.com/carpentries/carpentries.org/commit/7c0558b1252eeeef8899a0f0b0e7ba28f0098a11

**Comment by fmichonneau** [comment]
is this in your branch by chance?

**Comment by maneesha** [comment]
Yes... I hadn't refreshed my view on the live site :-(
