### ISSUE TITLE
stats on volunteer page need to be updated

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#390]
See 
https://carpentries.org/volunteer/

**Comment by fmichonneau** [comment]
we can get these stats dynamically from the existing feeds (except for number of learners but it'd be easy to add it). See how it's set up here: https://github.com/swcarpentry/website/blob/gh-pages/pages/workshops_past.html#L12-L23

**Comment by maneesha** [comment]
These stats will be dynamically shown in the new workshop page, to be launched in early September.  I've tried changing things on just this page but it messes up other formatting.  Will revisit this once the workshop page launches.

**Comment by maneesha** [comment]
Closed - dynamic stats are now on the [new workshop page](http://static.carpentries.org/workshops/).
