### ISSUE TITLE
display flag only if country

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#396]
Each of these files listed below creates a page using the person's profile information.  Most attributes are wrapped in a conditional (ie, 'if person.twitter' , 'if person.github', etc.) .  Country should also be wrapped in a conditional.  Otherwise we see a broken flag image:

![image](https://user-images.githubusercontent.com/829690/53758428-bc2db880-3e8b-11e9-99d7-90e31a493989.png)

So we should see this rather than just the `img` line.
```
{% if person.country %}
  <img width="64" src="../files/flags/{{ person.country | downcase }}.svg"/>
{% endif %}
```

Files affected: 
```
/_includes/community_profiles.md
/pages/instructors.html
/pages/maintainers.html
/pages/mentors.html
/pages/trainers.html

```

**Comment by fmichonneau** [comment]
It'd be best to use a template (i.e., a file in _includes) for this type of profile so we can re-use the same code across the entire website.

**Comment by fmichonneau** [comment]
I fixed the issue and did a quick refactor, so we re-use the code from `_includes/community_profiles.md` across all pages.
