### ISSUE TITLE
update data files section on readme

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#406]
This includes invalid `make` commands.

This also should include a link to the [data feeds wiki](https://github.com/carpentries/systems/wiki/data-feeds) for more information.

**Comment by fmichonneau** [comment]
This entire section does not apply for this site as it set up differently from the SWC website. I'm going to update #405 to try to capture this.

**Comment by maneesha** [comment]
This seems to be fixed, closing.
