### ISSUE TITLE
flags not showing up for upcoming workshops

### ISSUE THREAD

**Issue by gvwilson** [carpentries/carpentries.org-archive#419]
See screenshot for examples. There are also some workshops that don't have any location listed.

![Screen Shot 2019-03-24 at 9 25 02 AM](https://user-images.githubusercontent.com/911566/54880046-dae1f800-4e16-11e9-8254-fb45d99aef30.png)

**Comment by fmichonneau** [comment]
Thanks @gvwilson.

I fixed the AMY data for the UCSD workshop and the changes will propagate to this page in a few hours.

For the DC workshop, the instructors didn't use our template and so the metadata are not in sync with AMY (https://sateeshperi.github.io/2019-04-11-gwu/). @maneesha @sheraaronhurt @Talishask could you please follow up with them?

**Comment by maneesha** [comment]
Thanks @gvwilson  and @fmichonneau 
Closing this as we are following up internally.
