### ISSUE TITLE
changes to where links go from homepage

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#44]
On the homepage, there is a "ways you can engage" link. This currently goes to the join page. It should go to the community page now.

**Comment by ErinBecker** [comment]
The next link (the community calendar) should also go to the community page. Should link specifically to the calendar section of the community page.

**Comment by ErinBecker** [comment]
The "Carpentries Clippings" link (next link in that section) should go to a page where you can view past issues of the newsletter.

**Comment by weaverbel** [comment]
All fixed now
