### ISSUE TITLE
Alt image for people without a GH account

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#444]
If someone consents to publishing their profile but does not have a a GH account on file, they look like this:

![image](https://user-images.githubusercontent.com/829690/57074554-3c1ca700-6cb2-11e9-8cf3-300386ad2df4.png)

We should create a placeholder image (maybe just a solid color block) rather than a broken image.

**Comment by fmichonneau** [comment]
Yes, that's a good idea. We also have the gravatar ID available in the JSON file, so we could default to this and if the person doesn't also have a gravatar, they provide a default image. The URL for the gravatars are: `gravatar.com/avatar/{{ gravatar id }}`

**Comment by maneesha** [comment]
Thanks - I wasn't aware of the gravatar id.  Looking at their documetation, it looks like this will give us the gravatar if exists, or the "mystery person" gravatar.  

https://www.gravatar.com/avatar/123456789?d=mp
![image](https://user-images.githubusercontent.com/829690/57315255-34e60680-70c1-11e9-9b34-33c7401d251a.png)

**Comment by maneesha** [comment]
Fixed with 0a5f3bbf71a3de9f3d1d9caf2f779cd2c4ab2989
