### ISSUE TITLE
display Spanish-speaking instructors, maintainers, mentors, and trainers

### ISSUE THREAD

**Issue by raynamharris** [carpentries/carpentries.org-archive#448]
I'd like to populate the http://carpentries.org/latam-tf/ page with the community profiles of all the Spanish-speaking community members who are part of these groups

* instructors
* maintainers
* mentors
* trainers

What would I need to add to these lines of code to select for AMY entries where  "Languages" includes Spanish or Castilian? 

```
{% assign people_list = site.data.badged_members | where: "is_instructor", "true" %}
{% assign people_list = site.data.badged_members | where: "is_maintainer", "true" %}
{% assign people_list = site.data.badged_members | where: "is_mentor", "true" %}
{% assign people_list = site.data.badged_members | where: "is_trainer","true" %}
```

This is related to #447 but is in an independent update to that webpage.

**Comment by maneesha** [comment]
The query is possible, however we do not have consent to publish people's language.  We'd have to review our consent policy before moving ahead on this.  @fmichonneau  What do you think?

**Comment by fmichonneau** [comment]
Good point Maneesha. It also looks like the text of [our privacy policy](https://docs.carpentries.org/topic_folders/policies/privacy.html#id3) doesn't include people's language among the information we store. This seems like a useful thing to share with the community if people agree though. What would it take to add this capability to AMY?

**Comment by raynamharris** [comment]
Thanks to the discussion. This is a feature that we have been discussing among Spanish-speakers in the community, so I agree with @fmichonneau that is is a useful thing to share and that people want that information displayed. Do we need actual consent, in the form of a form or checkbox, that says we might publish what language someone speaks?

**Comment by maneesha** [comment]
We are having some internal discussions with our Leadership Team about what this means for our privacy policy and will follow up here once we have more information.  Thanks so much for bringing this up @raynamharris !

**Comment by maneesha** [comment]
Update - we are still considering what this means for The Carpentries from the privacy policy perspective.

I do think it would be useful to have a page like this though.  As an interim measure, @raynamharris  would you be willing to help reach out to community members to ask them if they'd want to be listed on this page? We could then have them submit PRs to our website to add their names to the  http://carpentries.org/latam-tf/ page.  

This would be a plain-text, names only list (to keep their PRs manageable).  Long term we will  be considering how we share community profiles, so people can choose to be identified (or choose not to be identified) by the different characteristics we collect (geography, language, skill set, etc.).

**Comment by maneesha** [comment]
At this point, our community has grown tremendously, and we've seen people teaching in several other languages other than English, which is super exciting! If we do something like this, I would not want to limit it to only Spanish.  I'm closing this for now, and will open a new issue when we consider more how we want to share our work in LOTEs, considering our internal capacity, our curriculum, our community, and privacy concerns.
