### ISSUE TITLE
table of all lessons with number of contributors

### ISSUE THREAD

**Issue by raynamharris** [carpentries/carpentries.org-archive#449]
At SciPy in 2018, I heard @tracykteal make a comment about how each lesson was an open source project in and of itself. She quoted a total number of lessons, but I don't recall the specifics. This of "suggest episodes for teaching demos" is the most comprehensive list that I've seen of our 26 of our lessons https://carpentries.github.io/instructor-training/demo_lessons/index.html 

There GitHub API has calls for extracting the number of contributors, but I don't know how to use.  https://developer.github.com/v3/repos/statistics/, but I don't know how to use it to _automatically_ print the number of contributors in a table like this.

| Lesson |  Contributors |  
| ---  |  --- | 
| Version Control with Git [(Source)](https://github.com/swcarpentry/git-novice/) | 205 | 
| Python usando datos de ecología  [(Source)](https://datacarpentry.org/python-ecology-lesson-es/) | 134 | 
| OpenRefine for Librarians  [(Source)]( https://github.com/librarycarpentry/lc-open-refine/) | 70 |
| ... | ... | 

Would it be useful to have a comprehensive table like this? Perhaps on the about page?

**Comment by agbeltran** [comment]
I think it would be great to have those stats! I'd also be interested in knowing how many times a lessons has been taught - this could possibly be collected from inspecting each workshop website (taken from the website list of past workshops).

**Comment by ErinBecker** [comment]
These both sounds like *excellent* ideas! I would love to see this information and have it publically available to the community. Are there any community members who have experience working with the GitHub API and who would be interested in working on this?

**Comment by maneesha** [comment]
Here's the [code](https://gist.github.com/maneesha/0c7318f071201db9edd8818b731c4916) to get this data.  I'm working with @fmichonneau  to add this to our website.

**Comment by maneesha** [comment]
And here's a preview of what this looks like as of today:

- datacarpentry/ecology-workshop 23
- datacarpentry/spreadsheet-ecology-lesson 81
- datacarpentry/OpenRefine-ecology-lesson 63
- datacarpentry/sql-ecology-lesson 73
- datacarpentry/R-ecology-lesson 146
- datacarpentry/python-ecology-lesson 130
- datacarpentry/python-ecology-lesson-es 133
- datacarpentry/genomics-workshop 47
- datacarpentry/organization-genomics 54
- datacarpentry/shell-genomics 69
- datacarpentry/wrangling-genomics 63
- datacarpentry/cloud-genomics 64
- datacarpentry/genomics-r-intro 41
- datacarpentry/socialsci-workshop 40
- datacarpentry/spreadsheets-socialsci 44
- datacarpentry/openrefine-socialsci 40
- datacarpentry/r-socialsci 56
- datacarpentry/python-socialsci 50
- datacarpentry/sql-socialsci 39
- datacarpentry/geospatial-workshop 40
- datacarpentry/organization-geospatial 48
- datacarpentry/r-intro-geospatial 130
- datacarpentry/r-raster-vector-geospatial 57
- carpentries/instructor-training 130
- swcarpentry/shell-novice 232
- swcarpentry/git-novice 219
- swcarpentry/python-novice-inflammation 230
- swcarpentry/python-novice-gapminder 143
- swcarpentry/r-novice-inflammation 145
- swcarpentry/r-novice-gapminder 160
- swcarpentry/shell-novice-es 187
- swcarpentry/git-novice-es 169
- swcarpentry/r-novice-gapminder-es 150
- swcarpentry/make-novice 63
- swcarpentry/matlab-novice-inflammation 53
- swcarpentry/sql-novice-survey 97
- swcarpentry/hg-novice 36
- librarycarpentry/lc-data-intro 77
- librarycarpentry/lc-shell 68
- librarycarpentry/lc-open-refine 77
- librarycarpentry/lc-git 67
- librarycarpentry/lc-spreadsheets 56
- librarycarpentry/lc-sql 72
- librarycarpentry/lc-webscraping 40
- librarycarpentry/lc-python-intro 108
- librarycarpentry/lc-data-intro-archives 10

**Comment by raynamharris** [comment]
Now in table form, sorted alphabetically rather than by contributors

GitHub Organization | Lesson | Contributors
---|---|---:|
Carpentries | instructor-training | 130
Data Carpentry | cloud-genomics | 64
Data Carpentry | ecology-workshop | 23
Data Carpentry | genomics-r-intro | 41
Data Carpentry | genomics-workshop | 47
Data Carpentry | geospatial-workshop | 40
Data Carpentry | OpenRefine-ecology-lesson | 63
Data Carpentry | openrefine-socialsci | 40
Data Carpentry | organization-genomics | 54
Data Carpentry | organization-geospatial | 48
Data Carpentry | python-ecology-lesson | 130
Data Carpentry | python-ecology-lesson-es | 133
Data Carpentry | python-socialsci | 50
Data Carpentry | R-ecology-lesson | 146
Data Carpentry | r-intro-geospatial | 130
Data Carpentry | r-raster-vector-geospatial | 57
Data Carpentry | r-socialsci | 56
Data Carpentry | shell-genomics | 69
Data Carpentry | socialsci-workshop | 40
Data Carpentry | spreadsheet-ecology-lesson | 81
Data Carpentry | spreadsheets-socialsci | 44
Data Carpentry | sql-ecology-lesson | 73
Data Carpentry | sql-socialsci | 39
Data Carpentry | wrangling-genomics | 63
Library Carpentry | lc-data-intro | 77
Library Carpentry | lc-data-intro-archives | 10
Library Carpentry | lc-git | 67
Library Carpentry | lc-open-refine | 77
Library Carpentry | lc-python-intro | 108
Library Carpentry | lc-shell | 68
Library Carpentry | lc-spreadsheets | 56
Library Carpentry | lc-sql | 72
Library Carpentry | lc-webscraping | 40
Software Carpentry | git-novice | 219
Software Carpentry | git-novice-es | 169
Software Carpentry | hg-novice | 36
Software Carpentry | make-novice | 63
Software Carpentry | matlab-novice-inflammation | 53
Software Carpentry | python-novice-gapminder | 143
Software Carpentry | python-novice-inflammation | 230
Software Carpentry | r-novice-gapminder | 160
Software Carpentry | r-novice-gapminder-es | 150
Software Carpentry | r-novice-inflammation | 145
Software Carpentry | shell-novice | 232
Software Carpentry | shell-novice-es | 187
Software Carpentry | sql-novice-survey | 97

**Comment by maneesha** [comment]
A live feed is now available [here](https://feeds.carpentries.org/lesson_contributor_count.json).  Next step is getting this as a table on The Carpentries website and the lesson program sites.

**Comment by maneesha** [comment]
This feed is actually a bit misleading as each repo includes the contributors to the styles repo that it's based on.  I'm working on modifying the query so that those contributors are not included in the lesson contributor count.

**Comment by maneesha** [comment]
@fmichonneau Am I remembering correctly that you had a way to do this query so only direct lesson contributions were counted, and not contributions to styles?  This question itself may change as we make changes to the lesson template.

**Comment by fmichonneau** [comment]
yes. But let's wait to have a larger adoption of the new lesson template before bringing changes to this;

**Comment by maneesha** [comment]
Closing this here and keeping it open in the [feeds.carpentries.org repo](https://github.com/carpentries/feeds.carpentries.org/issues/24)
