### ISSUE TITLE
extraneous "our team" in drop down menu

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#47]
In the "Our Team" drop down menu the first two items are "Our Team" and "Our Staff". Both go to the same page "/team" and it is titled "Team Carpentries". 

I think it should only be a single list item, should be called "Our Staff", should have a permalink "/staff" and be titled "The Carpentries Staff".

**Comment by weaverbel** [comment]
Out team also includes instructors, maintainers and trainers - how do you suggest we handle those if the link only goes to staff?

**Comment by ErinBecker** [comment]
Sorry @weaverbel, my issue was unclear. I wasn't suggesting that we remove the Instructors, Maintainers, etc menu items. Just that the titles of the "Our Team" page was confusing. 

I propose: 

Menu title: "Our Team"
Menu items: 
"Our Staff" - change page title within that page  from "The Carpentries Team" to "The Carpentries Staff"
"Our Instructors" - change page title within that page from "Our Team" to "Our Instructors"
"Our Maintainers" - no changes
"Our Trainers" - no changes

**Comment by weaverbel** [comment]
Ok, I have amended the SWC page to say Our Instructors - we need to make a plan to migrate this content over too (but that is a separate issue). But all seems well now so I am closing this now.
