### ISSUE TITLE
update "what is a workshop"

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#470]
Currently there are 3 buttons under each of the lesson program to request a workshop.

However, we use the same form and process now. So we should have a single button that says "Request a workshop" below the description of the 3 lesson programs.

page: https://carpentries.org/workshops/
target for button: https://amy.carpentries.org/forms/workshop/

**Comment by maneesha** [comment]
@sheraaronhurt  What do you think of this?

The buttons on the  https://carpentries.org/workshops/ page don't go directly to the workshop request form but rather to the "workshop" page on each lesson program's website. I would suggest keeping as is for now, and then when we get the new forms (currently under development) in place, we can re-organize all of this.

**Comment by ErinBecker** [comment]
I agree with @fmichonneau that there should be a single button that goes to the workshop request form.

**Comment by sheraaronhurt** [comment]
@maneesha I agree with you that leave it for now until we get the new WRF created. Once it is created, I would then like to have the one button as @fmichonneau  suggests going to the new WRF.

**Comment by maneesha** [comment]
Closing this as it is being addressed with the changes to the new workshop request form.
