### ISSUE TITLE
Copy of Announcing the 2018 Executive Council for the Carpentries

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/carpentries.org-archive#486]
Can we have a copy of https://software-carpentry.org/blog/2017/12/executive-council-2018.html on the website?

**Comment by maneesha** [comment]
Hi @rgaiacs 
The 2019 and 2018 Executive Council members can be found on The Carpentries website: http://carpentries.org/governance/

Were you looking to see more information there?

**Comment by maneesha** [comment]
Closing this - @rgaiacs please re-open if there is something else you are looking for.
