### ISSUE TITLE
Separate blog to its own repository

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#49]
Before launch, I will move the blog to its own repository. This will keep the blog separate from the rest of the website.

**Comment by weaverbel** [comment]
We already have blog.carpentries.org, I think.

**Comment by jduckles** [comment]
I shut that down awhile back. This will be starting with a simple feeling responsive theme, but only for blog posts. We'll copy the styles from this repo, but the posts and feeds will all feed from blog.carpentries.org. This will should help us avoid the future technical debt of Jekyll taking 3-min to build the website and blog at once.

**Comment by weaverbel** [comment]
Sounds good to me!

**Comment by ErinBecker** [comment]
@jduckles - it looks like the blog is still wrapped into this repo (through the _posts directory). Is this correct? Are you still planning on migrating the blog to its own repo?

**Comment by jduckles** [comment]
Yep, it will get broken out. Won't really change anything as carpentries.org/blog will just get redirected to blog.carpentries.org when I have that all sorted.

**Comment by jduckles** [comment]
Not going to happen soon, closing and adding to long-term tech plans.
