### ISSUE TITLE
Add SWC & DC Logos to the website

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#50]

**Comment by maneesha** [comment]
@jduckles   I know you're not actively involved in any of this any more... but I wanted to see what you may have been thinking of here.  Where did you envision the SWC & DC (and now LC too) logos appearing?

**Comment by jduckles** [comment]
Somewhere that indicates to people that there is a connection between SWC/DC/LC and The Carpentries. Doesn't matter where, but I thought it should be on the main page somewhere.

**Comment by maneesha** [comment]
Got it.  Makes sense to have them somewhere fairly prominent.
I don't know enough about design to figure out where this would look good or to make it happen.  Any suggestions about who might be able to help? @tracykteal @ErinBecker @fmichonneau @serahrono

**Comment by fmichonneau** [comment]
see #393
