### ISSUE TITLE
add information about the Carpentries Member Council

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#502]
as noted in UF-Carpentry/Coordination#119, information about the Carpentries Member Council is insufficient (or hard to find).

**Comment by elizabethwilliams8** [comment]
It is non-existent. We are just renewing this council, and September will be the third meeting in a long time. Already, we have changed the structure of who attends and are still seeking feedback on what is the most useful to include in these meetings. Soon we will be in a place to properly define it and find the most appropriate place to keep resources.

**Comment by maneesha** [comment]
Assigning to @elizabethwilliams8  for future follow up.

**Comment by maneesha** [comment]
I know this probably won't happen right away, but I'm tagging @Al-Obayuwana on this for future reference.

**Comment by maneesha** [comment]
@Al-Obayuwana  Are we now ready to publish information about the Carpentries Member Council?

**Comment by maneesha** [comment]
@Al-Obayuwana  Can we update information about the CMC now? I have heard there are meetings coming up but I don't know the details.  A web page isn't the place to list actual meeting dates but would be a good place to list what the member council is, how to get involved as a member site, what the goals are, etc.

**Comment by maneesha** [comment]
Checking in @Al-Obayuwana

**Comment by Al-Obayuwana** [comment]
I just saw this ping via email. I am going to add this to our meeting
agenda to discuss.
Thanks,
al
*Al Obayuwana*
Director of Partnerships at The Carpentries <https://carpentries.org/>
Pronouns: he/him/his
The Carpentries is funded by a wide variety of supporters. Consider
contributing to our mission <https://carpentries.org/donate/>.

The Carpentries <https://carpentries.org/> *- **We teach foundational
coding and data science skills to researchers worldwide.*
carpentries.org | Twitter <http://twitter.com/thecarpentries> | Facebook
<https://www.facebook.com/carpentries/> | Blog
<https://carpentries.org/blog/>

**Comment by maneesha** [comment]
@ErinBecker  Do we have information on the  member council to update now?

**Comment by ErinBecker** [comment]
The Membership Council will meet quarterly on the fourth Tuesday of February, May, August, and November. The upcoming year's meeting times are listed on https://pad.carpentries.org/membership-council along with connection information. The meetings are also now listed on the community calendar. @maneesha please let me know what other information might be useful here.

**Comment by maneesha** [comment]
Thanks @ErinBecker 
Could we say anything about who these meeting are open to, or what the purpose of the membership council is?

**Comment by ErinBecker** [comment]
@maneesha - Member Council meetings are intended for representatives of existing member organisations. We send out invitations to our current members about a month in advance of each meeting. That being said, we don't require any proof for attendance so technically they're open to the community. 

In terms of purpose, how about:
"Member Council meetings are a quarterly opportunity for Members to come together and share ideas and tips for building Carpentries community at their organisation. The Carpentries staff will also present a quarterly update on new programs, opportunities, and other topics of interest to Member organisations."

**Comment by maneesha** [comment]
Fixed with #1368
