### ISSUE TITLE
Instructor Development Committee update

### ISSUE THREAD

**Issue by elizabethwilliams8** [carpentries/carpentries.org-archive#522]
The listed members of the IDC are out of date and need to be updated.

**Comment by maneesha** [comment]
Thanks for this, @elizabethwilliams8 
Where do you see the IDC members listed? When @kariljordan  is back I'll check with her to update this.

**Comment by elizabethwilliams8** [comment]
in blog post: https://carpentries.org/blog/2019/04/new-idc-members/

**Comment by maneesha** [comment]
closed with #528
