### ISSUE TITLE
Break community page up into smaller subpages

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#53]
This page is comprehensive but long so I propose we break it up into smaller chunks for easier loading and less scrolling.

**Comment by ErinBecker** [comment]
My two cents: I prefer to have this on a single page, as I think it reduces the burden on new community members, or existing community members who are trying to figure out how to get involved with various groups. I think this page gives a good overview of all of the sections of our community and provides a nice starting point for people looking to get involved with something new.

**Comment by ErinBecker** [comment]
@carpentries/carpentries-staff - if anyone else has an opinion about the structure of the [community](http://static.carpentries.org/community/) page and whether this should be broken down into smaller pages, please add your preference here.

**Comment by tracykteal** [comment]
I also like having it on one page. I just had an example where I wanted to share all the pathways for getting involved, and it was really useful to point people to one page. I think having those internal links to subsections helps with some of the length. The subsections, also means that we could point to a particular subsection from another page if needed.

**Comment by kariljordan** [comment]
I'm a fan of the single page. When you click one of the links under **We do this through** it pushes you down the page to that topic. I think this is fine.

**Comment by weaverbel** [comment]
Ok, closing this thread.
