### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jduckles** [carpentries/carpentries.org-archive#55]
We do get some amount of logging and analytics from our CDN configuration, but I think I'd rather not use Google Analytics going forward. I'm investigating [Matomo](https://matomo.org/) as a privacy conscious alternative.

**Comment by weaverbel** [comment]
Have we got any further with this @jduckles ? Should we use Google Analytics for now?

**Comment by jduckles** [comment]
We get web stats from CloudFront and we're keeping logs. I'd rather not join the google tracking verse and we never looked at the Analytics other than summary numbers. We're getting those in cloudfront now, and we have all the raw logs if we want to process them in some other way.
