### ISSUE TITLE
Create a separate Committees and Task Forces page?

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#56]
I would like to see a separate listing of all committees and task forces. At the moment, these are scattered throughout the community page and it might be useful to present the complete list in one place. 

I have created a sample page but not linked to it from anywhere: http://static.carpentries.org/subcom-tf/

**Comment by ErinBecker** [comment]
@weaverbel - the rationale behind creating the community page was to provide a one-stop shop for people to get involved with various sub-parts of our community, without needing to know whether these were "subcommittees" or "task forces" or some other level of grouping.

Most of our groups do not "count" as official subcommittees according to SWC EC rules for subcommittee organization, yet still function as active and vital groups of our community. I don't see the need to make this differentiation, as I don't think our community members care whether the group they are joining is a subcommittee or not.

So I am -1 for implementing this page.
