### ISSUE TITLE
Exec Council need to provide info on where their proceedings are for Governance page

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#58]
We need a link for Exec Council terms of reference, duties, roles, minutes, etc.

**Comment by ErinBecker** [comment]
The EC meeting minutes are now linked on the Governance page (https://github.com/carpentries/executive-council-info/tree/master/minutes). They have also listed the roles of members with official roles (e.g. Secretary). So I think this can be closed.
