### ISSUE TITLE
brand the social cards

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#6]
link preview use theme icon instead of ours. I'll work on this.

**Comment by weaverbel** [comment]
Thanks @fmichonneau - favicon is here: https://github.com/carpentries/new-website/blob/gh-pages/assets/img/Badge_Carpentries.png

**Comment by jduckles** [comment]
Fixed the wee favicons for slack posts. I think there is more to do for social cards though. See 8e067aeaf8007772c72
