### ISSUE TITLE
Pull list of maintainers from AMY

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#60]
To populate this page which was created manually. https://carpentries.org/maintainers/

**Comment by ErinBecker** [comment]
+1 It will be very difficult to keep this page up to date as the Maintainers list changes frequently. Maybe we could use the same code that we use to generate the instructors page to generate a Maintainers map?

**Comment by weaverbel** [comment]
+1 to creating a feed to keep it updated.

**Comment by weaverbel** [comment]
Now done.
