### ISSUE TITLE
bold formatting not working on blog post

### ISSUE THREAD

**Issue by raynamharris** [carpentries/carpentries.org-archive#607]
@karenword's latest blog post has a lot of bold formatting, but none of it appears in the published blog...  any idea what is causing the problem? Should the bolding be changed to subheadings or is there another fix? Here's a snapshot of a few instances. 

https://github.com/carpentries/carpentries.org/pull/606/

![Screen Shot 2019-11-13 at 9 39 07 AM](https://user-images.githubusercontent.com/7544197/68789055-8257a900-05f9-11ea-9c8b-72690d1e2f6c.png)
![Screen Shot 2019-11-13 at 9 39 19 AM](https://user-images.githubusercontent.com/7544197/68789056-8257a900-05f9-11ea-9442-7f070f41f89b.png)

**Comment by karenword** [comment]
Thanks for pointing this out @raynamharris ! On my browser I do actually see some bolding, it's just very faint. I wonder if this has to do with the font we use on our website rather than an error in formatting?

**Comment by maneesha** [comment]
I can see the bold formatting on my screen:

![image](https://user-images.githubusercontent.com/829690/68878428-b1dbe380-06d5-11ea-843a-551d64f74dfd.png)

@fmichonneau recently put in a PR that changed the fonts on our site.  This might cause fonts to not render properly across all browsers. 

@raynamharris  Do you see the bold formatting on [this post](https://carpentries.org/blog/2019/11/carpentrycon2020-proposals/)?  

![image](https://user-images.githubusercontent.com/829690/68878680-2020a600-06d6-11ea-8db5-a15e90b09915.png)

**Comment by raynamharris** [comment]
It's so strange that I'm the only one with this problem. The headers look nice, but I don't see any bolding in that post either.  I'm using chrome on mac ios.

![Screen Shot 2019-11-17 at 9 11 40 AM](https://user-images.githubusercontent.com/7544197/69010983-5babb200-091a-11ea-8e93-dc1a6a5bceec.png)

**Comment by fmichonneau** [comment]
Hi @raynamharris to help troubleshoot this, can you please:

- open the developer tools (Command+Option+I)
- click on the icon with a mouse cursor on a screen (the top right icon)
![Screenshot from 2019-11-19 11-39-47](https://user-images.githubusercontent.com/5502922/69166495-55a40580-0ac1-11ea-8e02-4b0dbebe1dd0.png)
- select by clicking on something that should be in bold 
![Screenshot from 2019-11-19 11-40-17](https://user-images.githubusercontent.com/5502922/69166532-62c0f480-0ac1-11ea-892c-3e12e9502609.png)
- include a screenshot of the panel at the bottom right of the developer tools (especially the bottom part that says "Rendered Fonts"):
![Screenshot from 2019-11-19 11-41-15](https://user-images.githubusercontent.com/5502922/69166637-8edc7580-0ac1-11ea-8fdf-786518651dba.png)

Thanks!

**Comment by raynamharris** [comment]
Does this help @fmichonneau 

![Screen Shot 2019-11-20 at 6 09 19 PM](https://user-images.githubusercontent.com/7544197/69297827-01804a80-0bc1-11ea-8460-8f0d5cb95536.png)

**Comment by maneesha** [comment]
Thanks for sharing this @raynamharris 
I do see the bold style struck out on your screen shot but I don't actually know why this would happen.  Any ideas @fmichonneau ?

**Comment by fmichonneau** [comment]
Thanks @raynamharris 
Could you please go here: http://static.carpentries.org/blog/2019/11/trainer-training-2019/
and re-open the issue if the bolding is still not showing up.
