### ISSUE TITLE
Voting rights for instructors?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#64]
The [Instructors section](https://carpentries.org/community/#instructors) on the Join us page says Instructors must 

>  Teach at least one workshop every two years to stay a voting member of the Carpentry community.

Is this true? I was not aware that this was agreed to by the new Executive Council.  It's different than what was required by the old SWC steering committee.

**Comment by ErinBecker** [comment]
This was meant to reflect the old SWC requirements. It has not been agreed on by the new EC (or to my knowledge discussed by the EC). If it is inaccurate based on the old SWC requirements, could you please put in a PR to correct it? Thanks!

**Comment by tracykteal** [comment]
The EC is working on updating the bylaws. That is the SWC requirement, but I would recommend we just take that off the website for now. Do we have a 'roles and responsibilities' document for instructors that we could point to there instead?

**Comment by ErinBecker** [comment]
@tracykteal - we don't yet have a roles and responsibilities document for Instructors. The Trainers group has been discussing that again and will be talking about it at the business meeting this Thursday. Let's take this portion off the website for now.

**Comment by tracykteal** [comment]
OK, sounds good, will put in a PR.

**Comment by ErinBecker** [comment]
Closed as this has been resolved here: https://carpentries.org/community/
