### ISSUE TITLE
Include "Edit This Page" links on blog posts

### ISSUE THREAD

**Issue by angela-li** [carpentries/carpentries.org-archive#640]
It would be neat to include an "Edit this page" link on Carpentries blog posts so that individuals could submit typo fixes as PRs (and see where the raw content is), similar to the the ["Edit" button in bookdown documents](https://bookdown.org/yihui/bookdown/configuration.html).

Not a high priority, but could be a nice-to-have!

**Comment by fmichonneau** [comment]
Thanks for the suggestion @angela-li !

Blog posts and other pages now have a link "Edit this page on GitHub" at the bottom.

**Comment by angela-li** [comment]
Thank you @fmichonneau! Much appreciated 🙏
