### ISSUE TITLE
Update jobs page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#661]
@serahrono, we would like to remove the following open positions from the [jobs page](https://carpentries.org/jobs/) as we are moving forward into second round interviews with current candidates, and are no longer accepting applications:

- [Communications Manager](https://carpentries.org/communications-manager/)
- [Deputy Director of Instructor Training](https://carpentries.org/deputy-director-of-instructor-training/)
- [Lesson Infrastructure Technology Developer](https://static.carpentries.org/lesson-infrastructure-technology-developer/)

I was getting ready to submit a PR, but realized it took more steps than I knew how to do! Can you walk me through this in the next couple of days?

cc @ErinBecker

**Comment by serahkiburu** [comment]
Thanks for checking, @kariljordan, I added PR #662 with notes and would like for you to have a look.

**Comment by maneesha** [comment]
@serahrono  @kariljordan  Can this be closed?

**Comment by kariljordan** [comment]
Yes! I'll close it.
