### ISSUE TITLE
update queries for creating workshop table

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#667]
instead of using `if` statements, use a combination of `if` and `where` to make sure workshops with multiple tags are listed (but only once).

**Comment by maneesha** [comment]
I'll be working on trying this out this week.  I have a few test scripts ready that I need to play around with.

**Comment by fmichonneau** [comment]
great, let me know when you have something for me to review!

**Comment by fmichonneau** [comment]
@maneesha I had forgotten you had claimed this issue, and @elletjies pinged me this morning about some workshops not showing up after the 'email-automation' tag was added. I fixed it with https://github.com/carpentries/carpentries.org/commit/c9371a94629fe49f390c24f1d5a10088683a22e5 but don't hesitate to reopen if you had thought of a better approach.
