### ISSUE TITLE
Add contact info for Executive Council

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#671]
In pages/contact.md, could this line be added:

To contact the Executive Council, see [link to https://static.carpentries.org/governance/].

Then, on pages/governance.md, could a section on contacting the EC be added, for example just above or below the names of the current council? Information on how to contact the EC can be found at https://github.com/carpentries/executive-council-info.

**Comment by maneesha** [comment]
Thanks @lexnederbragt 
Let me know what you think of #682

**Comment by lexnederbragt** [comment]
Perfect! Thanks.
