### ISSUE TITLE
Home page: Consistency in language used about The Carpentries

### ISSUE THREAD

**Issue by libcce** [carpentries/carpentries.org-archive#68]
Language is slightly different, do we want consistency between these statements:

In the banner:
We teach foundational coding and data science skills to researchers worldwide.

Under “What we do”:
The Carpentries teach foundational computational, coding, and data science skills to researchers worldwide.

Under “About the Carpentries”, in the footer:
We are a global community teaching foundational computational and data science skills to researchers in academia, industry and government.

**Comment by maneesha** [comment]
This consistency should be applied to the About page as well:
"...who share a mission to teach foundational computational and data science skills to researchers."

**Comment by weaverbel** [comment]
@libcce Banner one is short to try to take up little real estate as possible. Footer one is longer because we have more room. I will fix the 'What we do' one to match.

**Comment by libcce** [comment]
@weaverbel @maneesha @tracykteal wonder if this is an opportunity to update the language to add "researchers and librarians".

**Comment by weaverbel** [comment]
I would be -1 on this at the moment @libcce - I think we should wait for the outcomes of the merger talks. We can put our own mission on the Libbrary Carpentry site. @maneesha @tracykteal

**Comment by libcce** [comment]
@weaverbel it doesn't hurt to ask these questions in preparation @maneesha @tracykteal
