### ISSUE TITLE
Linking Core Team page with Core Team Projects page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#681]
#673 introduces our Core Team projects page. In the current [team page](https://carpentries.org/team/) we have this sentence:

We work in teams to manage our day to day work and our large projects. Read more about who is on each team and what each team does.

The link to [what each team does](https://docs.google.com/document/d/1WThv85Mqhd7qin_fNrwbpe37UMzUy6K0oj72eEY4oK8/edit) goes to a Google document. Can we replace this link with the link to the core team projects page once that PR is merged?

**Comment by maneesha** [comment]
@serahrono is this ok to close?

**Comment by serahkiburu** [comment]
yes!
