### ISSUE TITLE
Update COVID-19 Blog Post

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#696]
In [this Slack thread](https://swcarpentry.slack.com/archives/C03LE48AY/p1583869718054500) @sheraaronhurt provided recommendations for instructors per this question:

- "hi all, whats the advice re: travel for a workshop when the university you are employed by sends a "no work related travel" notice?"

@sheraaronhurt can you add these recommendations to the blog post in #694 and add an update log to the blog post?

cc @serahrono: once the blog post has been updated can we push a tweet to the community?

**Comment by serahkiburu** [comment]
tweet sent out: https://twitter.com/thecarpentries/status/1237793106365501442?s=20

**Comment by maneesha** [comment]
Is this ok to close? @serahrono @sheraaronhurt

**Comment by sheraaronhurt** [comment]
@maneesha yes. Thanks
