### ISSUE TITLE
Update About Us page outdated 

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#697]
I was going through the [About Us](https://carpentries.org/about/) page and realised some of the information is outdated, including the number of member organisations. Opening this issue to remind myself to come back and update the page unless another team member is able to do it faster :-)

**Comment by maneesha** [comment]
Here's a list of changes to make - I can work on this. I've also noted who I think should be responsible for each part. Please feel free to add to this as needed.  
@kariljordan  and @elizabethwilliams8  you don't need to put in a PR yourselves. A comment here with the relevant information is good - I'll take it from there.

- [x] Update Executive Director's name @maneesha 
- [ ] Update count of member organizations and number of countries represented @elizabethwilliams8 
- [x] Update revenue percentage breakdown @kariljordan 
- [x] Update links to newsletter @maneesha 
- [x] Update link to style guide in handbook @maneesha

**Comment by maneesha** [comment]
Items assigned to @maneesha  are being fixed with #710

**Comment by elizabethwilliams8** [comment]
@maneesha I'll be able to get you an updated number by tomorrow. However, this number changes very often, if minutely. I think it might be better to say 'over 80 member organsiations' or over 90 or over 100 as we grow. Then we need only update when we pass a threshold of 10 more organisations. What do you think?

**Comment by maneesha** [comment]
@elizabethwilliams8  Yes, that sounds great! We can do this in approximately 10-site increments.

**Comment by kariljordan** [comment]
Thanks @maneesha! I'll have the information by Friday.

**Comment by kariljordan** [comment]
@Talishask is finishing up our financial report so she can help with the revenue percentage breakdown. Thanks so much for getting this updated @maneesha!

**Comment by elizabethwilliams8** [comment]
@maneesha membership number is updated!

**Comment by Talishask** [comment]
@kariljordan - I've updated the section on how we're funded. Please review and update verbiage if needed.

> We now have more than XX member organisations in XX countries. The memberships program generates 32.7% of revenue. Collectively, Workshops & Instructor Training generate 9.1% of revenue, while Grants & Donations generate 58.2% of revenue. These income streams support the work of the Core Team, workshop & lesson infrastructure, CarpentryCon, and our continued work towards The Carpentries mission.

@maneesha - Feel free to include links to other site pages as applicable.

**Comment by maneesha** [comment]
Thanks @Talishask !

@elizabethwilliams8  I don't see a PR or comment here with updates to the membership numbers (organizations and countries).  Could you share that again please?

**Comment by kariljordan** [comment]
Thanks so much @Talishask!

**Comment by elizabethwilliams8** [comment]
@maneesha I updated the number on the About Us page to over 70. Is there a different process it would be better for me to follow in the future?

**Comment by maneesha** [comment]
This page always listed 70 members.  Looking at [the members page](https://static.carpentries.org/members/) it seems like "over 80" (or even "over 90" knowing some members ask not to be listed) may be a better number.  Also, is the number of countries accurate? 
@elizabethwilliams8

**Comment by elizabethwilliams8** [comment]
@maneesha apologies, I updated the membership page, but not the about us page. I've updated the about us page now. I mentioned this issue there, and that closed the issue, which I was not expecting. Again, apologies if this is incorrect. I have had very few opportunities to use GitHub in the last couple of years. I am fairly positive the number of countries is correct, so I will schedule a task for myself to check into this when I have the space from the online workshops/COVID-19 project tasks. Please feel free to close this issue or leave it open, whatever works best for our systems in GitHub.

**Comment by maneesha** [comment]
Thanks @elizabethwilliams8 
I'll open this back up now, and update the checklist above to edit the number of countries we have member orgs in once you are able to check on this.

**Comment by elizabethwilliams8** [comment]
Thank you @maneesha. Since I cannot think of a member site in a new country recently, I am confident that this number is correct or very close to correct. Due to ongoing work and the COVID-19 response and mediation work, I would like to schedule a double check and update on this number at the beginning of the next quarter. I would like to schedule a recurring quarterly task to review and update both the number of member organisations and countries quarterly, so that the next update would be the Q3 regular update. Please let me know if this sounds like a reasonable solution for the current number and for long-term updates of these membership numbers.

**Comment by maneesha** [comment]
Sounds great, Elizabeth.  I just moved this to Asana so we can keep track of it there.
