### ISSUE TITLE
Assessment Page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#7]
I would like for the most recent assessment reports to be listed on the main Carpentries website. Right now when you click on the Assessment link it leads to the [assessment page in the handbook](https://docs.carpentries.org/topic_folders/assessment/index.html), and the handbook says our results are on our website. When you click the website link under learner assessment in the handbook it leads to the [Data Carpentry assessment page](http://www.datacarpentry.org/assessment/). What's the best way to fix this?

@maneesha should I change the link on [this page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) to be the Assessment page on the new Carpentries website?
@weaverbel can the Assessment page on the new carpentries website look like [this](http://www.datacarpentry.org/assessment/)?
@tracykteal do you have thoughts about the assessment page on the new website? I know you like being able to point people to a place. Will it be here, or the [assessment repo](https://github.com/carpentries/assessment)

**Comment by weaverbel** [comment]
@kariljordan I had already made a page that was exactly that - I can load that if you want. It could be on the site in a heartbeat as it is already built. Will wait to hear how to go.
@tracykteal @maneesha

**Comment by maneesha** [comment]
If we move the assessment pages [from the DC website](http://www.datacarpentry.org/assessment/)  and [the SWC website](https://software-carpentry.org/assessment/) to the new Carpentries website then yes, we should change the link in the handbook to whatever the new Carpentries website link is.

**Comment by kariljordan** [comment]
Perfect. @weaverbel please move forward with using the assessment page you already built. Once built if you could submit a PR to the handbook to have the link on [this page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) point to the assessment page on the Carpentries website that would be fantastic. Thanks!

**Comment by weaverbel** [comment]
Okeydoke !

**Comment by weaverbel** [comment]
Ok,  I have created the pages: https://carpentries.github.io/new-website/assessment/ and https://carpentries.github.io/new-website/assessment-network/ but I wasn't sure where to redirect the links from the handbook @kariljordan

**Comment by weaverbel** [comment]
Can I close this now?

**Comment by kariljordan** [comment]
I am fine with this as it is now, so we can close this issue. I will submit a PR at some point to update a few things, for example, DC's surveys are different from SWC's, so I'll do a few edits. We can close this now.
