### ISSUE TITLE
How do you get to the handbook from the main Carpentries site?

### ISSUE THREAD

**Issue by kmomar** [carpentries/carpentries.org-archive#701]
I wasn't able to find a link to the Handbook from the Homepage or any of the dropdown menus. I would recommend adding a link to the Handbook either to the homepage or one of the dropdowns.

**Comment by maneesha** [comment]
Thanks for bringing this up @kmomar ! 
You're right.  It is referenced in various places on the site, but there is no direct link to it.  Do you have suggestions as to where it could go? Your perspective with fresh eyes is very much appreciated!

**Comment by kmomar** [comment]
I think there are two places it could go: One at the bottom of the page where the links are, below the Code of Conduct and then at the top in the About dropdown.

**Comment by maneesha** [comment]
Great ideas, @kmomar 
Would you like to put in a PR?

**Comment by kmomar** [comment]
Hi @maneesha, I've assigned this to myself and will be working on it early next week!

**Comment by maneesha** [comment]
Fixed with #708
