### ISSUE TITLE
Difference between Join Us and Get Involved on website homepage unclear

### ISSUE THREAD

**Issue by kmomar** [carpentries/carpentries.org-archive#702]
On the homepage, the dropdowns Join Us and Get Involved are next to each other and it's unclear on first glance what the difference in the information will be. I would recommend either consolidating or renaming one of them.

**Comment by maneesha** [comment]
Great observation @kmomar ! If you have suggestions on how to reorganize these pages, please share!

**Comment by kmomar** [comment]
My suggestions for consolidating the information is to change the page that is currently linked to "Join Us" in the drop down to the heading "Get Involved" and then the page that is currently linked when you click on "Get Involved" should have a clearer identity; we can change the heading to "Community Overview" and move it to the Our Community dropdown since there are no direct calls to action and this page seems more informational. I'm happy to think this through further as well, and bring it up with the rest of the team.

**Comment by maneesha** [comment]
@kmomar  can this be closed now?

**Comment by kmomar** [comment]
Yes, sorry should have done it earlier. My apologies!
