### ISSUE TITLE
Donate link seems oddly placed

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#72]
https://carpentries.org/about/

Under the first paragraph is a sentence with a donate link.  This seems out of place but I'm not sure whare a better place to put this would be.  I defer to others if they think it looks ok.

**Comment by maneesha** [comment]
Related:  Is this page linked to from anywhere?
https://github.com/carpentries/carpentries.org/blob/e824b95d35521fbdfdfdf1873bfb7de264ec800b/pages/donate.md

http://static.carpentries.org/donate/

**Comment by weaverbel** [comment]
We can remove it from `About` as I have now made it a top menu item on all pages.
Can people please add +1 to remove it from `About`, or -1 to leave it there as well?

**Comment by tracykteal** [comment]
Looks like it's been removed from About, and +1 for that. Closing this.
