### ISSUE TITLE
Record of past Executive Councils

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#722]
https://static.carpentries.org/governance/ has a list of past EC members, but not of past ECs. I propose to add a link from this page to a page listing the composition and officer roles of all past ECs. I have prepared this list (2018 EC and 2019 EC), but am uncertain where to put it: on carpentries.org or in the handbook, for example as part of https://docs.carpentries.org/topic_folders/governance/executive-council.html. Suggestions?

**Comment by kariljordan** [comment]
This is an opportunity for our Communications Manager to shine. Please allow me to transfer this issue to the repository for the Carpentries website and assign it to Omar. Will that work @lexnederbragt?

**Comment by lexnederbragt** [comment]
Absolutely!  (Isn't this the repository for the Carpentries website, though...?)

**Comment by kariljordan** [comment]
Ah! You are absolutely correct @lexnederbragt! I just assumed it was the EC repo when I saw your name. That's my fault!

@kmomar please see above.

cc @serahrono

**Comment by kmomar** [comment]
Hello all! Joining the conversation here. I think it makes more sense for it to be a new page on carpentries.org, perhaps as a new page under the "Our Community" tab. This would leave the handbook section as a general overview of the kinds of work and resources about the Executive Council as a general entity. Let me know if you all agree and it makes sense for us to move forward with this idea.

**Comment by lexnederbragt** [comment]
Hi @kmomar! I support adding it to carpentries.org rather than the handbook. Currently, people looking for the EC now have one place to go: About -> Governance. Adding past EC members to the community tab would perhaps be confusing? Can we add the page without adding it to the tabs but only to linking it from the About -> Governance page?

**Comment by kmomar** [comment]
Hi @lexnederbragt. I spoke with @serahrono and we agree that it could also work to include these on the the current Governance page and have the Executive Council member list broken down by year. This would keep Executive Council information centralized. If that works, please send me the list and I will work on updating it.

**Comment by lexnederbragt** [comment]
Hi,

Here are the members of the first two ECs:


#### 2019 Executive Council

- Amy Hodge [Elected] - Chair
- Kate Hertweck [Appointed] - Vice Chair
- Mesfin Diro Chaka [Appointed] - Secretary
- Raniere Silva [Elected] - Treasurer
- Karen Cranston [Appointed] - Code of Conduct committee liaison
- Juan Steyn [Appointed]
- Joslynn Lee [Appointed]
- Lex Nederbragt [Elected]
- Elizabeth Wickes [Elected]

#### 2018 Executive Council

- Karen Cranston [Appointed] - Chair
- Kate Hertweck [Appointed] - Vice Chair
- Sue McClatchy [Appointed] - Treasurer
- Lex Nederbragt [Elected] - Secretary
- Mateusz Kuzak [Appointed]
- Ethan White [Appointed]
- Amy Hodge [Elected]
- Elizabeth Wickes [Elected]
- Raniere Silva [Elected]

**Comment by maneesha** [comment]
Hey @kmomar  @lexnederbragt  The [PR Omar submitted](https://github.com/carpentries/carpentries.org/pull/732) was merged. Is it OK to close this issue now?

**Comment by lexnederbragt** [comment]
Yes. Thanks! Closing now.
