### ISSUE TITLE
Links on the curricula page could link to the lesson webpages to make them more discoverable

### ISSUE THREAD

**Issue by rbavery** [carpentries/carpentries.org-archive#730]
If I was unfamiliar with the separate data carp and software carp websites and wanted to find a list of lessons, I would go to the "learn" tab and probably then to "Our curricula": https://carpentries.org/workshops-curricula/

It'd be nice if this page had thumbnails for each lesson and links to those lessons. Right now it just has paragraphs that link to each other.

The only way I've found to nav to the actual lessons is to go to the "Teach" tab and then to each individual webpage for software and data carp, which isn't as intuitive for the newcomer as going to the Curricula page. And could we call this "Our lessons" instead? To me, this makes it sound more approachable to a learner trying to find what they need to learn. Since we call the lessons "lessons" in the Teach tab, this would also make the language more consistent which is helpful for navigating a website.

Another thought, I feel like this "Our Curricula" page could be more front and center in the website. Maybe it could have it's own tab on the web header next to "About" called "Lessons"?

**Comment by maneesha** [comment]
Thanks for this suggestion @rbavery 
Some of this may require us to re-think parts of the website organization.  As a quick fix for now, what do you think of adding a link to each paragraph on that links back to the relevant SWC/DC/LC page?
