### ISSUE TITLE
Referring to DC and SWC as parts of The Carpentries

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#74]
When we refer to DC and SWC as parts of The Carpentries,  should we be consistent and say one of these?

* "Data and Software Carpentry"
* "Software and Data Carpentry"
* "Software Carpentry and Data Carpentry"
* it doesn't matter

This is inconsistent on the About page.

**Comment by weaverbel** [comment]
I will make sure we always say 'Software Carpentry and Data Carpentry'.
