### ISSUE TITLE
Create page that gathers info about online teaching

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/carpentries.org-archive#745]
I think @serahrono is maybe working on a similar idea of the handbook so my apologies if this is redundant.

Having a single page that lists blog posts and pages and other resources about online teaching would be very useful for our community. I believe it's difficult currently for community members to keep track of the information we provide via blog posts.

This page (even if it lives in the handbook) should be linked from the main page.

If the page lives on the carpentries.org website, I think it could be created automatically based on tags/categories used in blog posts and pages.

**Comment by serahkiburu** [comment]
hi @fmichonneau, the evolving list of all resources relevant to Online Workshops is now available here https://docs.carpentries.org/topic_folders/hosts_instructors/index_online.html, and has been linked to from the top of the official recommendations page

**Comment by maneesha** [comment]
@fmichonneau  and @serahrono  do you think this should also be linked to from The Carpentries main website?

**Comment by serahkiburu** [comment]
@fmichonneau @maneesha it is linked to in the first sentence in this page https://carpentries.org/online-workshop-recommendations/

**Comment by fmichonneau** [comment]
Thanks for putting this page together Serah!

I think we should also have a link directly on the front page/index page for carpentries.org that goes to the handbook.

Maybe we want to create a new section before the blog section?

**Comment by serahkiburu** [comment]
we currently have a link under the Teach item in the menu (TEACH - ONLINE WORKSHOP RECOMMENDATIONS), and then the handbook link at the top of this page. Wondering whether having a separate link under one of the menu items directly to the handbook page will be confusing.

**Comment by serahkiburu** [comment]
if you both think it won't be confusing to have this in two separate places, I'll go ahead and put in a PR creating the section you suggested @fmichonneau @maneesha. Let me know
