### ISSUE TITLE
Are community roles proper nouns?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#75]
On the about page we refer to "Instructors, Trainers, Maintainers, helpers"
Are all roles proper nouns? In this case should helpers be capitalized?

**Comment by ErinBecker** [comment]
I've been trying to standardize referring to all specific community roles (particularly those that require certification or a specific commitment) to be capitalized. I have not been capitalizing "trainees" or "learners", but have been capitalizing "Instructors", "Trainers", "Maintainers", "Curriculum Advisors", "Mentors", etc.

I would vote for not capitalizing "helpers" as it is not similar to the other roles in requiring certification and/or a specific commitment. 

@weaverbel - let's add this to the style guide.

**Comment by fmichonneau** [comment]
For comprehensiveness, it seems that "contributor(s)"  doesn't get capitalized either.

**Comment by ErinBecker** [comment]
Closing this issue. It should be incorporated into the style guide. I've added a link to this issue to the style guide google doc with a comment.
