### ISSUE TITLE
Instructor Map View Not showing Instructors from all locations/countries

### ISSUE THREAD

**Issue by Fnyasimi** [carpentries/carpentries.org-archive#751]
1. The instructor map view does not show instructors from all locations/countries. A good example is Kenya, on the map it shows there are no instructors from Kenya but on the instructors list I could see at least two of them. This will help people looking to connect with instructors in their region but don't want to necessarily scroll through the instructor's list (which will be growing overtime).

2. Some of the instructor profiles don't have a country flag showing where they are based and this could be a contributor to the above issue.

**Comment by fmichonneau** [comment]
Hi Fnyasimi,

We let instructors control the information they want to share publicly. 

Instructors show up on the map if:

- they agree to share their information in their AMY profile
- their nearest airport is documented in their profile.

The country in their profiles also needs to be documented to be shown in our list of instructors.

Thanks!

**Comment by Fnyasimi** [comment]
Thanks for the explanation above, well understood.
