### ISSUE TITLE
404 error on 2019 annual report link

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#766]
When I go to the [Annual Reports page](https://carpentries.org/reports/) and click [Annual Report, 2019](https://carpentries.org/files/reports/TheCarpentries2019AnnualReport) there is a 404 error.

The link should lead to [this page](https://carpentries.org/files/reports/TheCarpentries2019AnnualReport.pdf), but I'm not sure how to find this in the website files.

**Comment by maneesha** [comment]
Thanks for catching this, @kariljordan 
There was a typo in the link. I've just put in a PR to fix this.
