### ISSUE TITLE
Link only to Carpentries twitter?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#77]
The Join Us section on the About Us  page links to the Carpentries twitter but  not the the SWC and DC twitter handles.  Is this intentional?

**Comment by ErinBecker** [comment]
We should list all three Twitter accounts here. The same applies on the Contact page.

**Comment by ErinBecker** [comment]
Addressed on Contact page with https://github.com/carpentries/carpentries.org/pull/88. 

Not yet addressed on About Us page.

**Comment by weaverbel** [comment]
Have added to About
