### ISSUE TITLE
Suggestion from Carpentries Community in South Africa

### ISSUE THREAD

**Issue by elletjies** [carpentries/carpentries.org-archive#790]
A community member emailed me with a suggestion to add links to the 'local-africa' TopicBox channel somewhere on [this](https://carpentries.org/regions_za/) page. I know we have all the links here in the [Carpentries Handbook](https://docs.carpentries.org/topic_folders/regional_communities/african_task_force.html) - was just wondering if this would be a possibility to add it on [this](https://carpentries.org/regions_za/) page too? Also, for a person not knowledgeable of the Carpentries, the Handbook and Carpentries.org are two different things. How can we link the two?

**Comment by maneesha** [comment]
Hi @elletjies  It's a great idea to link the Africa page on the Handbook with the page on the carpentries.org website. Would you like to put in a PR for this?

Your other question is also a very good one and I believe is being addressed in a future communications plan.  Suggestions are welcome!

**Comment by elletjies** [comment]
Awesome! @maneesha I will out in PR for this (probably only next week).

**Comment by elletjies** [comment]
@maneesha I created to PR's 

https://github.com/carpentries/carpentries.org/pull/798
https://github.com/carpentries/docs.carpentries.org/pull/629

Thank you!

**Comment by maneesha** [comment]
Closing this - those PRs have been merged.
