### ISSUE TITLE
Instructors should be on Carpentries website

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#80]
Right now clicking Our Team --> Our Instructors takes you to the instructor map/list on the SWC website.
Instructors are common to Carpentries - should be on Carpentries website, not SWC website.

**Comment by weaverbel** [comment]
I agree but I need someone to help with this as there is a ton of material to move - images, bios, etc.

**Comment by jduckles** [comment]
We've asked instructors to explicitly opt-in to this page. So-far 360 have done so. I'll need to build some new Jekyll templates for this and add some data feeds from AMY to the `amy-feeds` repo.
