### ISSUE TITLE
"Our Member Organisations"

### ISSUE THREAD

**Issue by Denubis** [carpentries/carpentries.org-archive#806]
I was talking with @dvanic and we realised that there isn't a "Our member organisations" heading in 
![image](https://user-images.githubusercontent.com/243503/86417732-43559f80-bd11-11ea-8178-c63bc97a5c66.png)

I think it's important for us to show our members off (and be easy to easily search for members) -- is this a matter of adding a header link, @fmichonneau, or is this a data-entry job?

**Comment by serahkiburu** [comment]
Hi Brian 👋 member organisations aee currently listed under Join Us in the navbar -https://carpentries.org/members/

**Comment by dvanic** [comment]
I'm not sure that's a logical place to find them.. (?) - 

All of the other headings are about "Joining the community", which speaks to the next item in the navbar, "Our community"

![image](https://user-images.githubusercontent.com/3272378/86423104-3d1bef00-bd22-11ea-9d9a-cf786c835200.png)

**Comment by serahkiburu** [comment]
makes sense @dvanic, we'll take your suggestion and place Current Member Organisations under the Our Community tab cc @elizabethwilliams8

**Comment by elizabethwilliams8** [comment]
Thanks for the feedback @Denubis and @dvanic ! Great point!
