### ISSUE TITLE
Consistency in html vs md formatting

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#81]
Headings are sometimes formatted html style (`<h1>...</h1>`) and sometimes markdown style ('###').
Will this affect how pages are rendered especially as the site grows?

Example

html style:  https://raw.githubusercontent.com/carpentries/carpentries.org/gh-pages/pages/about.md
md style:  https://raw.githubusercontent.com/carpentries/carpentries.org/gh-pages/pages/community.md

**Comment by fmichonneau** [comment]
I think we should use markdown formatting as much as possible. It will ensure more consistent formatting. It could be part of a "technical style guide'".

I think the performance issue is pretty minimal as in both case, the files have to be parsed by kramdown.

**Comment by maneesha** [comment]
Agreed @fmichonneau that md formatting is easier to maintain consistency.  Is it important to convert the html formatting to md formatting now?

The examples I gave are for headings, but this is also true for other things like hyperlinks sometimes formatted html style as `<a href...` and sometimes md style `[text](url)`

**Comment by fmichonneau** [comment]
I don't think it's worth spending time converting from html to md at this stage. Moving forward we should try to make sure md is used whenever possible.

**Comment by weaverbel** [comment]
I will work to change to markdown when I edit pages but on the whole we can let this all happen gradually.
