### ISSUE TITLE
British spelling: "organisation" not "organization"

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#82]
Should all these spellings of "organization" be fixed?

https://github.com/carpentries/carpentries.org/search?utf8=%E2%9C%93&q=organization&type=

Note the [style guide](https://docs.google.com/document/d/10KutjajR-5RJfPAF8UQlxzcd8tx4PNFXH0acDFD2dBs/edit) itself spells organization with a z.

**Comment by weaverbel** [comment]
I will fix these and also update the Style Guide.
