### ISSUE TITLE
Staff contact emails not listed

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#83]
The [contact page](https://carpentries.org/contact/) links to the staff page to contact staff members directly but staff email addresses are not listed.

**Comment by ErinBecker** [comment]
+1 

Staff contact emails need to be added to the staff page.

**Comment by weaverbel** [comment]
I agree but we need an icon to use for email. When I add an email address now, the `yaml` renders it as an empty icon with a blinking question mark. @jduckles or @fmichonneau do you have an icon we can use for email? Or is there some other way we can list it in the `team.yml` file? See existing page with Tracy's email as an example of what needs fixing.

**Comment by weaverbel** [comment]
I have now used the Google plus icon which is not ideal but it allows email addresses to be added. I will do that till we can get an email icon we can use.

**Comment by weaverbel** [comment]
All email addresses added now with the Google Plus icon.

**Comment by jduckles** [comment]
Icon probs fixed by: 30d73f384 and 9db8e6d67660faa9e600e633efddc373025e89cd.
