### ISSUE TITLE
Response Correction for 2020-08-07-IDC-leadership-call-for-applicants

### ISSUE THREAD

**Issue by annajiat** [carpentries/carpentries.org-archive#846]
After applicants fill up the form for 2020-08-07-IDC-leadership-call-for-applicants at https://forms.gle/hssLFFHunLaAHa378

they are getting an outdated response:
"Thank you for your interest and application for the Instructor Development Committee! Interested in learning more? You are invited to attend an interest meeting at either 16h or 23h UTC on 3-April. Sign-up to attend on the instructor-development Etherpad https://pad.carpentries.org/instructor-development. "

We may need to 
- update the response by editing the form
- send the response manually over email to the applicants who filled up the form before the correction

Related page:
https://carpentries.org/blog/2020/08/IDC-leadership-call-for-applicants/

**Comment by serahkiburu** [comment]
Thanks @annajiat, we have corrected this.
