### ISSUE TITLE
Link in CONTRIBUTING.md on how to contribute via GitHub is broken

### ISSUE THREAD

**Issue by torockel** [carpentries/carpentries.org-archive#851]
The link `[included below](#using-github)` in CONTRIBUTING.md (https://github.com/carpentries/carpentries.org/blame/7c9bc9e0acc776b2a0d11916bac7418ee2d66ed2/CONTRIBUTING.md#L42) is broken. It should lead to details on how to submit a pull request.

**Comment by maneesha** [comment]
Thanks for catching this, @torockel 
Since we don't have explicit instructions on how to submit a PR, I've removed this note.  

Addressed with #852
