### ISSUE TITLE
Redirect https://carpentries.github.io/ 

### ISSUE THREAD

**Issue by robitalec** [carpentries/carpentries.org-archive#874]
Hello, I'm wondering if the link:

https://carpentries.github.io/

should redirect to:
https://carpentries.org/

When I'm on, for example, https://carpentries.github.io/instructor-training/, I can click using the navbar on the logo (far left) to get there. 

![image](https://user-images.githubusercontent.com/16324625/92977149-cd835800-f466-11ea-9aa7-f13be243c1bc.png)

But I'm wondering if a user was trying to move up to the home page using the address bar, just by removing "instructor-training", it might be useful if this page redirected automatically instead of a 404?

![image](https://user-images.githubusercontent.com/16324625/92977408-847fd380-f467-11ea-994d-80e4457e50d8.png)

I don't have much experience with Jekyll, so I don't have a PR at this time with the solution.

**Comment by maneesha** [comment]
Thanks for raising this issue @robitalec 

@fmichonneau  can you provide feedback on this suggestion?

**Comment by fmichonneau** [comment]
Thank you for pointing this out! https://carpentries.github.io now redirects to https://carpentries.org.

Where do you get a link to https://carpentries.github.io on the instructor training site? For me, clicking on the logo correctly sends me to https://carpentries.org. Thanks again.

**Comment by robitalec** [comment]
I didn't see a link there anywhere, just noticed it when editing the URL in the address bar. 
Looks great! Thanks @fmichonneau
