### ISSUE TITLE
special characters sometimes break anchor links on Community Developed Lesson page 

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/carpentries.org-archive#903]
The links between "List of Community Developed Lessons by Topic" and the indivdual lesson topics don't work in some cases, seemingly due to differences in how the lesson titles are "slugified" when they contain special characters such as `&`. Examples include "Carpentry-style lesson on how to use R, RStudio together with git & Github to promote Open Science practices" and "Building Websites with Jekyll & GitHub/GitLab Pages."

**Comment by maneesha** [comment]
Where is the list of community lessons built from? The file `community_lessons.md` makes it look like it's coming from `site.data.community_lessons` but I don't see that in the `_data` folder.

**Comment by maneesha** [comment]
@tobyhodges  Is this something that still needs attention? Do you know about my question above?

**Comment by tobyhodges** [comment]
Since the new version of the Community Developed Lessons page was published, these "lessons by topic" listings no longer exist and the issue can be closed.
