### ISSUE TITLE
Change order of repositories on 'Help wanted' page

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#915]
I really love the new Help Wanted page! 

Currently, the list of repositories starts with the general ones from The Carpentries, i.e. the workshop template, instructor training, styles etc. However, I suspect not many folks new to the community would no immediately consider helping out with these. I think they'd rather would like to start with the lessons. Could the Software and Data Carpentry lessons be moved to the top?

By the way, any reason issues from the Library Carpentry lessons are not listed?

**Comment by fmichonneau** [comment]
I changed the order of the repos on the backend of things, a different order should appear on that page in a few hours.

**Comment by maneesha** [comment]
As an update this PR (https://github.com/carpentries/carpentries.org/pull/919) is pending review by @tobyhodges

**Comment by tobyhodges** [comment]
Thanks for the ping, @maneesha. That one slipped through the net 🙂
