### ISSUE TITLE
Update metrics on WeDidIt page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#916]
The metrics on the [WeDidIt](https://carpentries.wedid.it/) page are out dated. I believe we have run workshops in 61 countries. @kmomar can you work on updating the metrics on this page?

**Comment by kmomar** [comment]
This page isn't managed from GitHub, so I have no way to submit a PR, but I have gone into the donation web interface and updated the three metrics using information from the annual report and am closing this issue
