### ISSUE TITLE
Add an "edit on GitHub" button for non-blog posts.

### ISSUE THREAD

**Issue by mr-c** [carpentries/carpentries.org-archive#926]
I'm a first time contributor to this Git repository, so it took me a while to find that https://github.com/carpentries/carpentries.org/blob/main/pages/member_faq.md is the source for https://carpentries.org/member_faq/ :-)

**Comment by maneesha** [comment]
@fmichonneau  do you know why we have both `page-fullwidth.html` and `page.html` as layouts? The "Edit on GitHub" option only appears on pages with `post` or `page` layouts.  I can add `page-fullwidth` as well but wanted to check if there was a reason why things were set up differently.

**Comment by fmichonneau** [comment]
these layouts are coming from the theme we are using. The `page-fullwidth` is typically used for content that takes up the full width of the page (e.g., https://carpentries.org/workshops/), the `page` layout is used for content that doesn't take the full width so it's easier to read longer text and there is room for a sidebar (as in our blog posts).

We could move the chunk of code to edit on github to the default layout so it would appear on all pages.
