### ISSUE TITLE
Link to most recent issue of newsletter

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentries.org-archive#95]
Under the 'Blog' drop down could we add 'Newsletter' and have it link to the most recent version of the newsletter? Then it would be a place for the most recent news, and the links have all the information on how to sign up for the newsletter too.

e.g. https://us14.campaign-archive.com/?u=46d7513c798c6bd41e5f58f4a&id=21eaf480e5

I just don't know if there's a URL that will always take you to the most recent issue.

**Comment by weaverbel** [comment]
The 'most recent' link would need to change every two weeks unfortunately.

**Comment by fmichonneau** [comment]
That's a goo idea. I'll look into whether we can use Zappier or some other way to automate this so we don't have to update the link every 2 weeks.

**Comment by fmichonneau** [comment]
See #108 for a partial solution.

**Comment by weaverbel** [comment]
This page looks broken to me @fmichonneau - the archive isn't showing and the footer is weird.
https://carpentries.org/newsletter/

I have tried switching to `layout: page-fullwidth` instead of `layout: default` but both seem equally bad ! Sorry if I broke something in trying to edit the page.

**Comment by fmichonneau** [comment]
yes, something is wrong. It renders fine locally, but not on the server. I spent 1 hour trying to identify the issue yesterday but didn't find a solution. I'll look into it more.

**Comment by fmichonneau** [comment]
the page now renders properly (at least at https://static.carpentries.org/newsletter/)

**Comment by tracykteal** [comment]
Yes, the page looks good. Thanks @fmichonneau! Closing.
