### ISSUE TITLE
Move language about sponsored membership

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#963]
The become a member page includes the language below in the context of Platinum memberships, but should probably be a more general statement about the possibility of getting a sponsored membership, even if not Platinum. Assigning to myself for follow-up
`
We provide a limited number of sponsored memberships for institutions with financial need and for institutions serving historically underserved populations. If you believe that your institution is eligible for support, please send us an email.`

**Comment by maneesha** [comment]
@ErinBecker  Is this the exact wording you'd like to see? Where on the page would you like it to appear? I can take care of this if you let me know.

**Comment by ErinBecker** [comment]
@maneesha - yes this is the exact language to use. Please put it near the end of the page, but still within a section that is general rather than specific to Platinum memberships. Thank you!
