### ISSUE TITLE
BlogPost-DC-Workshop-Iran

### ISSUE THREAD

**Issue by ElnazAmanzadeh** [carpentries/carpentries.org-archive#968]
Blog post for “The Carpentries” website.
Well, it was my aim for a long time since I started to learn basics of programming in Python in 2017. I was excited to teach whatever I learned to other people and extend it. I am an analytical biologist and I have a lot of colleagues who were searching someone speaking Persian to learn programming skills from. I think learning in maternal language is crucial to make the lesson more efficient. Teaching Data Carpentry could help them to make their own way in their research projects and it improve quality of their studies. I planned this workshop two months after I got my certificate as an instructor of The Carpentries. Because of COVID-19, the workshop in Iran should be online to. Good for me! I participated in several online workshops around the world such as US and South Africa to learn and have experiences in teaching in online workshops and become an experienced instructor. “Data Carpentry – Genomics” workshop was planned to run in September. I asked an analytical biologist who was an expert in R programming (Parastoo Modarres) and a computer specialist who could help people to install required for the workshop (Alireza Heidari) to help me teaching in this workshop. Most of the participants in this workshop were biologists with almost no previous experience in programming. So, I prepared training videos for “Programming and Plotting with Python” and “Introduction to Command Line” and let the people to watch the videos and have time to solve problems in exercises before the workshop and get ready for it. I wanted them to get the most from the workshop. We ran one full day workshop on 09-07-2020 and we covered “Data wrangling and Processing” lesson. We had challenges with internet connection and installing software. However, supporting helpers make their bests to help all the people to keep up with us all over the workshop. It was great to hear good feedbacks from participants and I was happy, though I know that I should set up more details to have least challenges.
There are people who are asking me “When will be the next “DC-Genomics (Python)” workshop?”. It is extremely exciting for me. I am planning to run another DC workshop in Python next month and also run “DC” workshop in R, Software Carpentry and Library Carpentry workshops in different universities of Iran. I am also looking forward to run the first DC workshop in Turkey in collaboration with my friends. Thanks to Support team of The Carpentries for all their support and helps all the time and for all details.
Hope to get better day by day.
Elnaz Amanzadeh Jajin

**Comment by kmomar** [comment]
Hi Elnaz, Thank you for submitting this post. I believe you have been in touch with @serahrono, but if not, we are planning on publishing this early in the new year (Most likely within the first week, Jan 4-8). I will create the PR and then send to you for approval before we publish.  Thank you again for writing the post.

**Comment by kmomar** [comment]
referenced in PR #972

**Comment by maneesha** [comment]
@kmomar  Can this be closed with #972?

**Comment by maneesha** [comment]
Checking in @kmomar  - can we close this?

**Comment by kmomar** [comment]
Hi @maneesha sorry I totally thought I closed it... Closing now!
