### ISSUE TITLE
Expired memberships listed on Supporting Organisations page

### ISSUE THREAD

**Issue by elizabethwilliams8** [carpentries/carpentries.org-archive#97]
Of the organisations listed on the page these institutions are no longer members:
Met Office
NLeSC
University of Melbourne

these institutions have membership renewal in process (but technically are not currently members):
BIDS
University of Miami

I differentiate because it may be ok to leave BIDS and Miami up, but the others should probably not be listed (sorry that I do not know how to remove them!)

**Comment by weaverbel** [comment]
Have taken them down but this page still needs work. @jduckles can you please provide me with a list of current members so we can be accurate here?

**Comment by elizabethwilliams8** [comment]
@weaverbel I have addressed this in issue #98. However, I won't have all the logos, descriptions, etc...immediately, so would we want to just publish a list for now? I will send you one, just in case.

**Comment by weaverbel** [comment]
A list is plenty. Maybe even better?

**Comment by elizabethwilliams8** [comment]
@weaverbel emailed you a membership list already; replied to it to get it to the top of your inbox.

**Comment by tracykteal** [comment]
Addressed in #118
