### ISSUE TITLE
Updating Member Organsations

### ISSUE THREAD

**Issue by elizabethwilliams8** [carpentries/carpentries.org-archive#98]
I will send out a form to gather the logo description and URL for our current members (not already on this page and not on the Typeform below already).

[This Typeform](https://admin.typeform.com/form/hzi3U8/results#summary) is the one I am using, and there are 12 submissions for members that have come on board recently (I have added gathering this to my onboarding workflow).

**Comment by tracykteal** [comment]
updated in https://github.com/carpentries/carpentries.org/pull/118

Either before or after it's merged @elizabethwilliams8 could you check to see if the Membership lists are correct? They are I think at least more updated than before.

**Comment by weaverbel** [comment]
Anything more to do here @elizabethwilliams8 ? If not, this issue can be closed.
