### ISSUE TITLE
Add Code of Conduct Transparency Reports to the reporting page

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/carpentries.org-archive#989]
https://carpentries.org/reports/ should perhaps also include a link to the reports at https://github.com/carpentries/executive-council-info/tree/master/code-of-conduct-transparency-reports.

**Comment by maneesha** [comment]
Thanks for the suggestion @lexnederbragt 

Tagging @fmichonneau as the Core Team Coc liaison - are you OK with this? If so I'll make the change.

**Comment by fmichonneau** [comment]
yes that sounds good. Thanks for taking care of thsi Maneesha!
