### ISSUE TITLE
Updating Community Overview page

### ISSUE THREAD

**Issue by karenword** [carpentries/carpentries.org-archive#997]
The [Instructor Training curriculum](https://carpentries.github.io/instructor-training/21-carpentries/index.html#the-carpentries-community) points at [this page](https://carpentries.org/community/), and with updates happening there it would be ideal to bring this page up to date as well. However, I'm not sure of the best way to do this.

I suggest adding:

- [x] Community Facilitators
- [x] Executive Council (I know they have their own page, but a link here would help make this a 'one stop shop' for ways to get involved)

I also suggest creating a section for "currently inactive" roles (or whatever is more generally applicable), which may potentially apply to
- [x] Assessment Network
- [x] Champions
- [x] Lesson Infrastructure Team

Finally the "network" section of this page is redundant with [this page](https://carpentries.org/connect/) so should probably be deleted to avoid unnecessary maintenance.

**Comment by maneesha** [comment]
Thanks for bringing this up @karenword 
I am tagging @kmomar  and @serahrono  for their feedback.

**Comment by kmomar** [comment]
Hello @maneesha and @karenword. I agree with most of the edits above. However, I would say that the "network" section serves a similar purpose as the Executive Council section being proposed. We can simplify it, but I would like to keep something similar there or a link to the connect page.

**Comment by karenword** [comment]
Thanks @kmomar -- I'm not particular about precisely what the updates look like, and I understand from @serahrono that broader improvements may be in the works. In the meantime, however, our curriculum currently points new trainees here for the ["What is Your Role?" activity](https://carpentries.github.io/instructor-training/21-carpentries/index.html), so it would be ideal if minor updates could be made in the interim if those changes are going to take a while.

We are broadly trying to identify 'canonical' sources of information that need to reside beyond our curriculum, and I *think* this page fits that description for basic information about our community.

Relatedly, I also just discovered that this page needs to be updated, and also is not linked from the page in question: https://carpentries.org/inst-dev/

**Comment by maneesha** [comment]
@serahrono  and @kmomar  Are you OK with adding Community Facilitators and Executive Council to the [Community Overview page](https://carpentries.org/community/) as @karenword  suggested above, along with the currently inactive roles?

**Comment by maneesha** [comment]
Also @kmomar  what is the "network" section you've referred to above as serving a similar purpose to the Executive Council section?

**Comment by kmomar** [comment]
@maneesha at the bottom of this page https://carpentries.org/community/, above the calendar, there is a section called "Network" that I am uncomfortable removing from the community page, even if the information is available on this page (https://carpentries.org/connect/) as I want to ensure we don't assume people will go to the connect page. Perhaps the best solution is to link to the connect page rather than keep the network section.

**Comment by maneesha** [comment]
@kmomar  I think that is a good idea. Since we don't have completely identical "connect" page and the "Network" section, we can make the "connect" page include all the communication channels, and then have the "Network" section just link to that.  I can work on a PR for review.

I also wanted to see if you're OK with adding Community Facilitators and Executive Council to the Community Overview page as @karenword suggested above, along with the currently inactive roles.

**Comment by kmomar** [comment]
I think @karenword's suggestion is totally worth doing

**Comment by maneesha** [comment]
Thanks @kmomar  
Do we have information anywhere on the Community Facilitators?  Anything about who they are, what to do, how to get involved would be great.  I can make the update if you share that information.

**Comment by serahkiburu** [comment]
hi all, following our Community Orientation session in March, I have several tasks in the pipeline to update the page, and Karen's suggestions fit in it. If it's ok with everyone, I can take ownership of this issue.

**Comment by serahkiburu** [comment]
@karenword https://carpentries.org/community/ is now updated, please have a look and close the issue if it addresses your request satisfactorily.

**Comment by maneesha** [comment]
@karenword  Is this ok to close?

**Comment by maneesha** [comment]
Checking in @karenword  Can we close this?

**Comment by karenword** [comment]
Thanks all -- yes, I think this appears to be up to date!
